workload:
    main:
        podSpec:
            containers:
                main:
                    env:
                        OPS: Minecraft
                        WHITELIST: Minecraft
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITUV4VElLNnY5UENPR29j
            MDhYdU5UYlFQODVTZHZxT3Q0SXZDRG1CcUdnCmllMGc3UU80SG1sYmg5dnZYMWFT
            eWZvaVU2bHJ4OFdVOFZ3ZWRPN0VZMDAKLS0tIEp1cU51UW9jNEV0K2VpWTNLY09F
            aUZiOG1ubWZaSllhSHV1ckhFaUQ5NWMKRnz3lLi0fZwBJSpADDrOp8rV46WU2fwJ
            mTdLMSiP+mY6hKrymqRtvTyePrAwKNPwKORmYYe/zCEiJXEOqxwBuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T07:53:46Z"
    mac: ENC[AES256_GCM,data:BrfGWW7g2cGbXTzCE9qqzV7mVNapIusdt5X7Xq7d6h3ngba8YIDlW0fj8fX882QUpwl29V91VHlrmuBZj/b5lyby8FYwU4+WGbYnYLxE5Buy7+vLqVi1ifAc8DMZsvKx4G2PqMYsyuRPU5UVgd8B3pSDNha4m/OuwS4uKPGk2ps=,iv:UgflNDro2dK/p5y76EFG/E8B6NraDRMZTN7Gym3oOvo=,tag:XZWUBQzT1Jcv3bdpdu/ZVA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
