apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/ks.yaml
  - grafana-alloy/ks.yaml
  - grafana-loki/ks.yaml
  - kromgo/ks.yaml
  - truenas-exporter/ks.yaml
  - smartctl-exporter/ks.yaml
  #- gatus/ks.yaml
