apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/notifications/discord
resources:
  - namespace.yaml
  - helm-release.yaml
  - prometheusrule.yaml