kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: renovate-secret
    namespace: renovate-operator
stringData:
    GITHUB_COM_USER: ENC[AES256_GCM,data:xrfxHOlQT4+sCxA=,iv:/pwD3OnQaiAJCgdh3jDXGP0RQp7uVgsUmms1Und6uxA=,tag:qBaOVd4abdV0XzJhn23sPw==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:7XHoBkioLGyAxCieAG3OfO4ELw1IDt3bzstGNh0mekPsNUDccebn3DLQ2kWUmBjEJCfBw+86r542R1e9saJSsxLiDZaCUdRPUMEpmNVMUkA2HmotaOGILkvZzg0S,iv:03sfZIv7kGoh5D3OXyOBdQl1i6dVMf3wnHbs829GTEU=,tag:FxTcim9ciEb9HtSAU/X2rg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:RWkM5OlUPr/iKsNTtPdlGa4Ab60QOFTe+DErqU09EmH2n/lgHMdPdbHKS04JDXpcBZNS/B77ZcBy+q4S8TTqCJHqHo3zDt8fIIf645XzTCVDQh0ufI6+fSmGhFfX,iv:UhOul44ND3fpyMNIUgdf/TAH+K6fMp1XTonQyNeBLWs=,tag:1iEazDEXwWfos32Hyij8IQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZGwzcW5IUjBRWmpGMCs5
            YzhXWTNSemViYngwUUh3QUdZdkUwQkhGTVNJClVYWEMwWWM1SlBlTkY3OVk2TTlk
            NTMzdU0zbkxsZFlLVzBQdjFpTXA0Mm8KLS0tIDZQMTVJdU8zS2V6WHUveEh5Y2dP
            TDd5OFhQdDhTbkFWMXpaNDBoa1Q3dEEKuyMWUr+W01/4hOd7aQWd48Q/K++MB1fx
            XDkv1jznbQr6bEKhiv/ZLWlvzuK60kJU3CAYvepT2rEIJLqW3isuXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T17:04:50Z"
    mac: ENC[AES256_GCM,data:He9zvm1oFGOFkzbK3Z4Dji17sT/blP/OyHqpEMNqdKsmp0tEOuOOLwKOFlXwsZWdlUQt7OWiZex+QVzvV2GfEaUAOmlN6cquX3dHZXo6jsn2vjM69f25C42QpYevetXnwuiR943K/mlvEHDJps9nSBIeoK6OwLBVCo+djR3y6RY=,iv:tsxKmCvLlUCDGMBMVoTcFyDezfd43PXkij6b3LcAj6A=,tag:FqZpPGvjnd7aNtzLAKJedg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
