apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - minecraft-java/ks.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - sabnzbd/ks.yaml
  - sonarr/ks.yaml
  - minecraft-router/ks.yaml
  - home-assistant/ks.yaml
  - zwave-js-ui/ks.yaml
  - webserver-dynmap/ks.yaml
  - homepage/ks.yaml
  - metube/ks.yaml
  - lldap/ks.yaml
  - authelia/ks.yaml
  - librespeed/ks.yaml
  - speedtest-tracker/ks.yaml
  - guacamole/ks.yaml
  - pgadmin/ks.yaml
  - signal-cli-rest-api/ks.yaml
  - bazarr/ks.yaml
  - hermitcraft-java/ks.yaml
  - immich/ks.yaml
  - it-tools/ks.yaml
  # - actions-runner-system