apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-alloy
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/observability/grafana-alloy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

