---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - actions-runner-controller/ks.yaml
  - boemel-runner/ks.yaml
  - test-runner/ks.yaml
components:
  - ../../../components/notifications/discord
