apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:k4vYm0HLvVO1FM3qkY4TBAW39nrRL/vYWJfy/ZP1gnmU2AslpCmRpkVpPUgY/kut5QjDmppJ/0IxJGHqtiNQDFMwRe1v8f65YSuR+HDKD23JSJ9SvOKJ+RVdKHDviz74dgIWH8cWvQ/cbHEZQySt16dm3CeMBihE4E2umcF3g4TnguCtVC3Vyg06dViQn4GTadq6/ES9COLPuglMtJ4SyWbicmwQz8B7OqkAPCvM8dphSFoOZbnHNM0hM3WhIDWpB0usT6uVJYCSBpcyiRbX8ht6oKJVQwm/6WuBjfnpRZPnyoEpPTxHw5u/55TBB6wmYIWDKO20ELKBGqOXp5pza+McXmEuSjcjbvhYb5SixB9esPifDNDUHO+TaAfuj5HX,iv:MT+DUn94SPWjHcQ5rplUihhVrPZQxzFcvr1YGtWsj9A=,tag:mpxuS7q6TwT4GbvJ3UMiaw==,type:str]
    identity.pub: ENC[AES256_GCM,data:eYvsRXlFWeDd+Au6JO6KhWJ3UjSyMd/3QZ32KhEh4ITVxhobyfJL2pv9WY9N/0QbDXMUyv1BDEUqheE2Rc7xtlhsJoJaX8nubYqc2LpKu/bP8yeJfAxWatcKZ1JTlhttjPkTbAH73eBERoFxYIuUUUdihtWinTQTRwhwuCdgIYPVanHLptYOE3UUAYBAc2HNUU+OwFtMmD/GJVJXJPZ3pHGuyEqTy8WR1IgotNkASzunwxgniONKuh7//OZB1Tp8GqEv0nJiRmAHpk7h6w==,iv:3XiTKsWe/FOYloW+YOZIABCNIvoXfdTrL7j/NZbkLbI=,tag:Cov4mRz4O6Miy6Q2Pbdv5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:NfJuDshsJffColFZPpNaQMqJZuXXR7HFx0ztbyaduDkxn3lqJmNc2NKb5G2vt1Uwl+AF1qX9bnxT8ImDCYJGoeita6ZD5UlTDLbNjlzrFMVFEL3zSG1af1X7dD+IlKMtz8BY+0bI8Zc6bFVj25ApFwuM378/t5P6684ssg7jw/FuhqhjnWkBTsS4wAMtCt/LtiDpkKGDCIHh3AqPh6KXo5FPi33oLUIe1W6q,iv:MLLpaPyS46am4UnYieGZR0pJwtyKaMejl8LC+LAF8K0=,tag:87tYRT3wPW0V/LAFf/Gpww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXU5aFJDNUYrMUZWRm0z
            bnJxcWZMZ0RqVHl2NklKQ0hOK0NGR1BrQ3l3CkJYeXB6WlhUVVp0czlIYTRRbXpB
            R0JhMzI5T2owanBHMGtIYis1eFNEamMKLS0tIFdSUnhuR0o4MXoxU0xXMFFXVjV3
            TnRnWUNFR0RtanJEU3VtczNkN0UzY1kKpAzMvRmp1jJ8aL2vrI7flOnyaIk5OCDt
            dDVKQSU6GJU9La7tN8DgbctTpJ3tVlaop2Amm8o1rW+W5b0bdbu/6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T17:50:38Z"
    mac: ENC[AES256_GCM,data:dsx9nVD2zeDDMKB9REomHhWCs1x/s3XH1oxACfaC3nUwqlQE/oRR8PvthIOiesAZXh6Z7wYnW3YkeCTApHTx2EQZxeSBdOgbU1vbtlGxCkmOLmr+YyNGuaRDYY+mOfBgd27qjjicnea1FQzGPVOaYBm4JATbWaMwLGfWf6Y1qQU=,iv:mQJygN+f0SDM5hRBlMaTtDMQX9zt/D53S0JtAIISUKs=,tag:lokhmpY0V+6hXu++YJMnmQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
