apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:J+IR8Y7AqAA4MyAbTu4cAYZQm8henUOEf4EghhEXdt1dsrSH0uOufbd2HEUlLSkODIYOEPLw99hD8zNBfwJ3+6DZLGSlb3LVRWm897I6Ndq3DvhcqkpV5XlsmPwZzofdyaN+HtLdJGl7iQlTneOen1naA4fIsp7KFbmsdty7oanpS9/08zLM+rdmj3eFGWLMGsIVEg0B0ztK61+8eEqD0F8vfKLe/60UxD3kJ+7SEz66nPyK27XrX8sk216ItZmAWrKs+DdVvx8/T/OjF3D1rXier8dM1V/cNO04BWmW6WJm8WeDw+nZfM6mBz8d3khCJq3PexEdaoHepRTp3Bfnf9u92odux/dD3/fiU6mltV367TiQwjc4fF2Lzs4lNByw,iv:17EoPegQh3mEm9qYAmmfz8w0yGk4NNx/t5q+M6YGCVY=,tag:qwhrqO/tTSTV7moa/06tug==,type:str]
    identity.pub: ENC[AES256_GCM,data:AKMEwNTV7sXBEWb+g5AlaoUyfDR+v8N/BU0FDYhAHw43cP7QpcSNro0+SaU97dM/CRrEhmPul3Ri0tmNJp+RXa5FdqVeQGdxkmD7aAOClaAKkwYOXAcY62rX6HlOJ2hVAS3hDgnXV/RjFbCRYpGyhlmR6e4vCNJlD3VAWolvkgIoOKK2WvB2Wz6JvwlWL1fzhcFcxsZB6IPVRyRHsszMPl2QImUxy8K2vZG7bs1X0L3C22zE2dznoge87jXyU3JF/ZDRvzOpTEmdSAyBbQ==,iv:RaXKpcm9i1u7ML5TL1BoSVFCXKHzZwzoLyktOceffsE=,tag:gxLuIWD13ZhtZsRxPmw3Lg==,type:str]
    known_hosts: ENC[AES256_GCM,data:GEWMuAMk1rJF7lJuUfHbdzz7OVmXmCOj5HQeUdEFSEKuzZ13n7dlRmrghuzfQOxszQDcjTN1Mp/4cak0cCDVMp6BeGR26niQlAAvRKW/YZRnMu8Q/Dvxnil5N2NniEl979UwxaVkd1/wznwfAy/tW0QtM18jYIGzYyQO06XopfJNzd9Scpd41ZfjAPJY16sgS0Vo08r6X8RvCD3w8LVmiYBlgfEMNMMRWLYW,iv:7Sx7KEbwV2s+D6wxpBR1V6g/GxuWH1ITn0mE7BhKbRA=,tag:+ggIoE9ae/4gL4nMeKSdUQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacEpxa3VFNGZ0bXlTaWVo
            VkdGUjVlNU9uRkphK2xXZ09XOEVIYVZVVGxjCkNGZHRpSGt1cy9lM3BDZ2tDSGNW
            UVpYZFIrUEtUdzN5YUM2NEd6TmpQY1UKLS0tIExCMGFqbXI5VkhEUk9TM0hVbkdJ
            U1IzOXRucHlkQUZlNjFKLzdsNmlOcmcKcLjALWLkIQY46X1AwkCfuPjeNx/1jUR1
            fq8o7RTqIZI4Tdq6lWKlbW3jg5DgJqsZTDYDGcVLCYZLEzMjidk2kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:05:37Z"
    mac: ENC[AES256_GCM,data:OjYSAqHY+//yP8b3yZCEV05q/wN/vllKShidDr8OXzvdupTDYG6aCLhecYFWmWHPKZ6zaRv6fu1kojnMCHJsCD5xZvZa7nrCWNJbwXtaggBM3zC/h/kVVBd7/XmwXhAaTnt2VKgo8Jj5rtuMkXYZ4al2hFrSBAD7rktIi0kOF8Y=,iv:INpFeifaBs4qdJJ5cTnx81EPoh62QI+pDASe8UMtthA=,tag:tj/h6NUYqtnzfGVshHiYEw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
