apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:v39B95JnORGHI6J3DwU6ERD8WdBkpI35gXCWc0UDVX054C2b1SCrF00RYC6nqiQxl+D1iDJUvzfVPAt4ZK6Oqozq80yDlC15d2Cdx8E07f2AhsZog+SQMMy1sU2HAFUjAFPBx1W3o9l2vmZUyilEc2o6JBy0rtA8VrAirOVivcve1NeyhICX4bgF2s0YE1hiuzQHTWeDG0DKTZ+3ECAbF/loCiGyVsp4Ufxa5dAfP6XRQp4JsmlAC6evjlHRSBwR229f83SXJibFDbSBLkHhj2aijOKv8ieCY7KVzPNFuGBKDG1lc0yeL4ON04TjqoeOdqELEPCIDSNk95OH0b3QXc9Zb/HaiAuAkjAnDk1OFwyf602h1GrJTkJR08JP0xti,iv:yAOt+cQQJqUjVDQP91thtKabvY9Cni0ONWbBpK07MCQ=,tag:vv7x/SS3Wrn5sAVE4Xh/7A==,type:str]
    identity.pub: ENC[AES256_GCM,data:63UjRXn37+lUCgXpYcU43bEFeAEpWAZAkcI6N2gYDf560Xp78ME96/3gvNN1twUowtD8KHJlBjCg3xZCKJvd6zRwHLFC1uQC00Pv1UResvDTgIBDZsQH4bhnMwvlyMQ2IqNSM2tY1Ce3oQSlxasKH4QEGGdlTrVLY6N98AHuvKoBsoOexhrIdq14C5biOfamjgHQCXVHpg6EzVteZG0YakYp1tOUrns8tDqExg08HpoYai08vnNLwoXu2LxktrwHKPkm6ceRjUoUVilKcg==,iv:ScafQYe9OvNKmeo2PqwG82VvpHDzRQp+rNhk69YBsng=,tag:xH94tZ+nV4znYXKNMPu5Cw==,type:str]
    known_hosts: ENC[AES256_GCM,data:hAAM/6r3zK9Gcvi7lmmLP45qdCNZKsd1ZmYSQjWbUzzpBq/GtMfYeVFN4/3heLvylkjz+a+37bqhjETWYeoG/7oxmAXohW84szNqAygrQRFTHRsFsfiimpNwQ4+Hyt06FH4YRwVp6AdJ4vq+F4++lJvkrohnS8fmTAieMCgICuodyDWDK7KNeQA+tqBXryGLKWO8TXRf6MEgsLEf6222zvi1t8S10CFFESiN,iv:EwXzD/0XFVeOIZBSthMbUSdg1WhBrmo4qODpHn/zAy4=,tag:0F3h5pjIH/H5yFgmIy6Z9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RVJDM0Z0TENBdDJBc1Fx
            ZlhWbmVoeFdPd2ErTFYwTmhLQXVXUDM0QkFNCkhYS0trQkRLVXJtdTM2cjNjcktu
            N1ZuSjlseit2L2ZMMFpzMTJ4aWZocTAKLS0tIFg5OUJ4RmVDTWxyMHZKRFhyam5V
            VE4yaE01YkplV3hJeFJORkhqbDYrencKEZsFeAfxQUvVw5Fl4QC5xJUHoOuMqU42
            CKuy8fxeoUaUB2wiDAbSXtNw65qRqRv41ClDRXUW/ly8tjwJyfXWLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:30:33Z"
    mac: ENC[AES256_GCM,data:VDuA0IaNWIF/RhVqEHHNCiE9j16jjXUnG42emB6uhll2FqxZfOHWvb/fj2HYR657aVL3DVuKpiXYIUzB7L6GLGd65FKoB+MyPgOVswhKnZn0mBhV4xM8HN1suiO2YFecof1Gr47aocdKrOoo1bvG5ClZEO0o4C8+EhK3MLoI1po=,iv:Q1JHpi7pb2NvGrTeT3DOrcQeiR8NIJWTyTiM2d+njrs=,tag:oampUX5cLjRH4/iZUXeovg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
