apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jv51vOOVT4FGA7pk/k38IjhPi89QMV/07aNO6/Jnx/qG85wLa6tM82mlrpuSdwHTCQMM2Ue3pvSj4n+4is0LpmcGf8v3TrWPT48mcZfEhHRNuIFSHfjZKlElQr14SAZW7zh8irrDrWI3YILq9sul8Z7og1xOHr1FvWwimPIe2Dikluau/Apy3p+uHE1XiC4rvIBAaYCGLkY+3uziTPOFJYEG0ney0PDDYPZNplFELoEENMiXOR17Do+qKpQHYYGC28qUM7YNL0wlnlFRW8d9Qw1aIMh4Ld/GkXHQNND9D0MBr+gqbBHiMoDosnj4wVkayK/WdIhQniDa7jXsldunfE8AvnoYXs2pSjqLMSytqrY5Q3womECT/u0tFyZWVVER,iv:2dHvzKxZPa54JmZhbhcdWaM7zzhvUicPd+8aesfJygQ=,tag:jkw6OXxVUSs/YxbspaqPTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:fUmYC/FhmCEibvJe0LKyvfr7O1jnIZYuLVDAi4ddDsb+5XNf9fDq54UQbvUBmZwUlzuaTmKadZF+0ZYrWZtTN8J0bCvq5wGYf7WxYJqKgL3FjFppCcmy2xxcYMVZt6ygo/OGdjpQEevNfPJCRAzqe75OBeP7Y+assAUxhWDdvlNRdxfFkMxHsQH97ClYYyrYi4//ZS3HRBVhJeccYF8RfeVccDzwttJJEsGevHBi5GfYFGfNMT5/0x9o9i83zBX/Au5U9FgX1fduQ4aVDQ==,iv:Y14tXI9JP38dJbqk3hAbmSfOAvXursDL5FSWWJO7Bd0=,tag:LqL5ZlYvi2GNvhRES8Iadw==,type:str]
    known_hosts: ENC[AES256_GCM,data:B4PsrbIPsMn/GOEXlUi6h7MvoudphP2Whs/JGg+3uAuwmsMP1KcC7IIgiETjn5RY4t7ENyLWb0rYJ+x6cCsdZBqHZ4aqPIdoywgDoJn6bWVsFV/FiRQNbOKtg7Z0TaMaMU+X7auBssM5wEFbJ3x/AFmCM3I8fEUnp4gV+DX2F5aMoPdcLLnFJag41XNduZvxy+XfBzD9sB49YqUI5xlR8yPBeQ008RWihZb0,iv:rPzzS6TMUZHIUbX4BwX2Oa2LV2AW1GJwC9ANHlaIBwM=,tag:og0lIPSERYMiwMv8Sly3zQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSlEzSjUrN1M1TTNXYVlC
            Ny9tUTNCSjdqNEFiMDdHUXIycmYvMnY1NjNRCnZRbHNXMDlVUlVxM1FwYU1YNDYv
            THg1ZlgvNThibnJzSzFuN3ZPbmQwcGsKLS0tIGcwUEtNSkZlcEdweXlYR3JiYk5u
            MW1FSHBHUHlLL3VvYk1NQjVRdWtEWUUK1pdhpDxdXNUe32C1+gEViXYySJxky9CH
            HIEi7CFpSV6NfrMe4DvsrDehUwjOkIN9w4CLKhKrwmh5sY+i+Dhkrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T14:05:12Z"
    mac: ENC[AES256_GCM,data:CYgFQu0mOZTyrmybAa+6561ddQvWzzIcgVleDOMUiXqz3BrESgtF5L4TG+xPCPK3OQE3DouBxsao77kaAg3Da5mKE1k0AVB2lUlokz1BxXEpWja+2EzO/T1fMNhuF6lsCWKQ1uTZ+ebs1BvmSSG22Sj5UmpiH4o81ig+GXv5FWs=,iv:BNlBBu+ZHlZghSOEt6lHRJCyy5MsgMsyBOeAi0AR6j8=,tag:jXigrt0RV6xwmlpi/wgixg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
