apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vDCvGWVAYomkfKuR46t1pgIen/p2UBqlEIiTrw6PACGDSrkJ22WV4FCT7NWCrKXXWf0aPDwfbuoFOeC7ZTertkQGvhfZANT8vgdGFpbgjM7uDUnCBM8QzcPuJcP3MoVCdfxAX16sbe5E4rKCzhW2+dWVFAlJBqhiDPh2wqzZm5qJ57Jbp2ERyp133BRmZl3oicCfLlnTRrWdFHpbee1Sb9jctNhQq2mrsZAjXFUAZ+AYqREEhh3f5wsey1NyD9F32tS/SPk5LY0h7DP//r3UeohXI2+AMnq/KmuGcHa/O0f9nf3JLxFvsUGSd5et24nY824a+4QXf0ZAoR4Txhl72HOujv4JGeeicgMKR5uuMB+FiN5NsoIHIKWl/hxH1TSY,iv:iKQ0hgGh3180zXFGznBLPmuGOY4SCpAm55vnqWQAf3Y=,tag:9T3sLs/qHx7LKdP5hmM96A==,type:str]
    identity.pub: ENC[AES256_GCM,data:cEMg3TEjfnvxwflR/cCHzA4/gtjzMjAGEKVTsbORR39AIB/S5Z7o3c6+UjxfeMLVWid2BvcbuK9ltNyGmxi59y6N16/goV+BQ0sc2OGXAkXeet/y5ZycSrXAO/Kr2VK0cK4yx2Njqz1N6GW0Cq2b6CcUByzWZZ5eHE+2LMxGmsP5RVtUi7IeifeRWP1JqzkiI83mnyw7/XtOSMiDnkn7ES303Uq7pkoyFHf5VllUModC6N8fNfM5GMD8z6jOE1MOB3bp4j9+sHcmukuJhg==,iv:0oP992j1ghL4H74web7PMmORKhz+Qq1H1Akgkg4KQd0=,tag:ZMn8nvOXadZ6IvC+kQUg1Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:uWj62lsGbsooRjVl70CapuvaBY6wz/qVDSh6ZSmWPQG/NiR1A45adjh03GyD7QjjUz35TnU1BvBJc9T2GpSZm5YQxDz4ij7+y7/iVcRULimPC+rMqydSFwSKMADK4HAWAMm1GVR18r68ULxyRaa9O54rHTSHP+/T+kYwI0AHEVE9TIn6DXN0cM6dbBbICDM+uPD7oSWxnVcvxgkLQFGsPv0wUrzlgCCBRL1A,iv:P52yVrD0um7Yg9dPWd8jagOaESbxY7Kx+a84yIoStno=,tag:rF7KtZp+Sk8eyRC/XS2rVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRGJnbENNZ3JRLzV6ajV6
            Q0xqV25rbmhhNXhzVmZacjFvZU9LcUw5Tlc4CkVPUlFFSjRPSWtUdDEzWW1pZG9Z
            d0JFeGt1eGpsYW5MMEZ1YUloMDk5VDQKLS0tIFRrMFhIMnd5dE5XQTFBYmRyOFFX
            UVdxaXNwc3p2S0YvL2RGUkpPeFYrNUUKUbima9f212P5D7igr6lvpQ8yi1CksVGg
            o7Z5/IIoVNZONUnhty8SVNccQbFm3qzhAvnaTG5xJBfMxbm6g7Q96A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T23:29:02Z"
    mac: ENC[AES256_GCM,data:5wxT5TPbpdzWIQWqPQu84hti0wNW4du8ENFmRlthPloa3VTPC9izefDPr6ET7RjEzFvzbfxJ5v9w45nZihz2RCW2tVeaHCQmbOU2fCp411zbwtdIxd4SVqUTDzoudF7/QdPoHatjIsp7Hk4pnTuuvJI9VxPm7ExrQaFnSypBaX4=,iv:ScRwWhzLOEGchS85qPuXro25CJruUz4cLoN352aD7WQ=,tag:AQXPx2SPG8+Keb0LYnZDew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
