apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+anOMpzHFKKLeFkbEEfvyCcqWaZLBGCCtgR7igNH4zDQbZtSy8+P4jhVAtJGmDlihaMlF3WBc/8fUxG020dqraSxQ9/tWMwuXgD3PBAjU6kZLIxAsHNjdvOSlDHEuiOVdr9MWo73sd3K2Lpnbh4+Owk0JD4KI4s1uI4U7TKaGeuhLx18lzjep6LLHFejLtlvELkejx3qBwsXadmlDNNruDpoiO9iNgfDnVvV8hsc+r87MI1xYf08KuhoW1G1+UF85TQCXXktQ5jerIzgx5rj6m9SktVZ4gTzebFottz2q/wXIdTr6od7cStKkCTJDpUpZpLIDCDrPascPq+fVZbIkrx1lAPvRWY1jV7tCSggdUoITWjsAdsCCdZhxezR1Dxx,iv:kZFQMQvso1eOSAOUlF4DJZxTacsI8MXyjuUvvjTI1VY=,tag:JS3xyka7YE/JDsRjYRtsrg==,type:str]
    identity.pub: ENC[AES256_GCM,data:3cLvKM4QBxgHVVzIbCCGXZxBDL9NqyqSAYLK/MyCzCUX/xhtzjcfhhJeMI6czev26uHUtOyDxAn/JcrjxwvXVZ8Ymj1hzIazSb6EhXuDTZkEjDoXfVmrEYKHSzrG9+Bcql3NuKYOrApbjJ0yFxUCeKTdCQit3WIrw7ta/8GaZAdGEKsJhsjPdStw6h/8rYkxHfXckABkAeJ+mKJkE1nqmmRGg9RIHsHa4D2YR6pmQbVSii1PcTnDect8rkSPkaRsETlu3J907EniPVDxog==,iv:duXdq9GzJUcg7S/qxwVZ2v+n2iPFn8tibBp2/845n5w=,tag:3iNt7wHiieQyytEmt/NN+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Rwleoo7mRlrPZlnjwdHItjOa75aZjsQ9DDb+0+rSO45q1vfL34RZsqSqr51YKFPp/Uytg9Mn3QIxDqP1Ed4f1H93KCDulDat/e1woT90LBZUYis9lK9iVVejwVz/bFT3nirvX+tPLXAnfpLeoWZs1k7ZYZiDLqjv6DhQfPmH9PY0ENXvCNjAS4n6rVhy5k8EWFUB8rkukEh4t/aYfKTcAqNQ9/wcHwtOpCqP,iv:m1tzgVDWtS+7DhuSw7YMlAekjKDI6r/DZmHCELrdnnU=,tag:cIYgP41pXAVvL/T92uDqfQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWElCTU9jKzZldHRxY3Q2
            Q1FoaXN1R1l1WlRyOVQrQVFYOUNzY05aK2dvCncxYlBXeVFUY3Z0SHlNaTYwYUVs
            cHBjQjUwanB0ckxYSUpiNE1zOW9JWU0KLS0tIFg2SWw2OUpYQWh2aXYrNGVLLzl2
            NWMzYjZKdytFdWRiVjh5NEVOVVd5NWsKR5/JnhYeADwjGk4FFyx4/F/czMdVfK9H
            PwERpBPBzKCCUBWCKOVrRSWXMDTCiQx9sb3ae0cygADO8YxihwWh0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:41:38Z"
    mac: ENC[AES256_GCM,data:mLRbQU6YzrQqCqXPHheSBfw+tl3nGJ91pazaHQHRyEb2BYF+cjpR2Q7EwebBKHMRvGA4HeyYX7r1s22A8784p6+Faq1zUaVgugrfEu8rTlq2ak+K53XM+lVKgO/7kN2v/MVfYyTDwBiuTtL1gFJVXXsak4Z7jFDcdZ56AMoOe3k=,iv:U4gLnXFbGwBWr8Y6X6WgNmBcyLmiIwypBjk9G0j4dI4=,tag:wQ1FZrY3H7CDBMRG4C+AFQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
