apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YVpxKCb47WbhepLH/lsxPLI5RL6ZKEYzwaMmVOmijff7nIU87WE/uOdOhxQ8Ya1LXutyb0BjQJ+PlyVkZEGIBgBuE/T6J3fsRz2WNFAzX2g7UEMSYjGf6CraLw0uqXzvuphV6pufsgF/jwI8HLLSsFcTNOzzoxBZp8KMUbx/KbTc9uyqvFE0QowLuXuWrsqUIb0TdiIBvHICYF9LALWD2B07stwft8rGDpNxkWgnmz1TpvPg++DjNUuDqal1XVQiqy1p7YUs1pbWA4BahO7/stDSmQLE5IeaiQqp9xOvV0tDCAxK17+549uvfJRm1pNc68z8S7X2tzhju7Qdsa+KyqVy3P3VPNuh0Pi+kSxJHgnb/4PtKUNQjVPHEED95ZJ3,iv:slducJl0Koeyl12UdmpY6dvTgSDWb8Glh6B4JgcWdb4=,tag:uDplo68sX0eRzge5zJp/yQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:VHqVjkGzgbctqIZlZ1xVNCgPK4rctG2MLm+LISMD+eJHTu1kBHS/XasfsJwLCsoME5U1+urdvLl2Qjsgyqm9mrwBRB3iCnBl3zm82lkLRjX0RIClweIDG1VMadpqsEZ+NOm5CTM1dTxZmsJK0I533clPqg4AG3d6XfaJEC2m3N5JufLlZZSu3y2QjVmGuslEjdL2Ljs0xIyNFK4sy9nymIQXesWTHDsVZahZML037jtFGI47GS9aqCWkyFrE+9/mWA4KhAJQB7b/vMiSBQ==,iv:xaigwluB7DyR9U7sqeF+JKq324l519CHdu13IO9RN0w=,tag:5lmW8eUwl89+OJSnJvJXkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:LKNAlDEMIa7xUTcvE5LiN25usudZlmuY0HQ9QRPKYYHl2qCwJE1P3Yyk1QCxCB+kjC3toT6z22dSW7K8p86egHBycKosgUn8MXtbL2QL93oku3yRPPt/KDNso9T+udpIE6uDlG3z29YK5E6krsnj+BpC1FhwJrvZ1RApbjCg8AIBgSU6ctb7ikizSKRrP/1f+JIJyLYMvlrYdt1DqbAuAWWYIPOciT9dtHpY,iv:wDYt/TrveHTT+CrnXaJqoHch2uzvIPEcsvtiXc2fdyM=,tag:T66Vb4TRTYy4e05G09lF+A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV3VubjVIM3FhUDBlM3VQ
            bkR6K1M3NXVoUHNreFFFdWJCNjZFelBFdUJvCmxGOU9DcDRKZEZMOGgwSGt0d0Rw
            NEk2NVp1R1BYSWVnZFhHaTlUL09TNEEKLS0tIENMU2t4c2FYNGJtOXltTUZJa3lL
            VmRHOTU1dVRxS1lNRnZtblp2c3hYdDAKop3D/eTiWjkg4a8bvWa6OhltFez7wCF0
            tuECPlCtGHYqEKrqKaLyvmrpN4tLYs1sQDaqTYNiSM0HATtl3o4kPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:10:30Z"
    mac: ENC[AES256_GCM,data:q9kzmsm583iDrSveDxXx3q2zUBK7TIpo+EdDUJK2MzNQaseg3ds1a8gTC97M94+Hok/v9DHj5y3G8RHuK6LsuN0ciMQgLrULJQG2Q7NR1yUez9w1UgBYW+ISnKv0GCWoAQIZZXpXvb717qK/5h2vkcLmuuz5Mo80RrGADJIjTBQ=,iv:FLLdjjDFMjn8sfvMGI3dXDnPNkY8vtTKJWpycn31Ndo=,tag:jLFyEGcCpVW5KFVBdWS2Dg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
