apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:V9fFOZHbtw3jV3Yns1TyMrlKxi8zKDB+aqRZtDLFyOnT8fPKlYKQHwuX8oLwd/X60nnPT4Lvnvzr5O949H2znznbLTdGY9d/IGtC6dTkhRlghI6N5eS2yMIiuRi+Ej4NYC3hGWDwDs2aHV6RlMO48gKyxBidREmf4QUt76qlhUpLmZSgzK4m2YIj2x55WeDrn2OaJVPJeszdHyNyVryxumlqVB8hSNu+vExjUDlf5MAghkiOo+/LZQXk9Y/dXGqY9xd8QYJuz5A/oW6SsIiMWE7GgjX8aKvYCf1DDObN4SJlzJAbHoi3BsEx/qhRkCJpL9h+ffmG2W6HGfIk1WGmr6T/x/m8iU9RHG1L+NdVW8SqVblKwkkDuRf4lFGQlnP1,iv:OY3+lGH14gXMwK1mTuIA/QlNBeG+OLTrEtZLdxP/khY=,tag:wygZDNQbO/ka7Qyv1Ist3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:0+9kUm4zk4A/B6VkyafGOpl9R96eyhSAW+F+uTXwTbgoZGhcZ1bTJatmcIbcz0AlqUGXM6tZ+K4esqxREqaDg6ReYRfDt5OBdyzN+iF00yDryX8cqtzcK41YcP9PJ4YIBjPPimloBTLF/T3WoR5mSOa0PwX8EBYHpglHqub1nIkXeDgGZnJKQ+59ks4lQdzh67iHY9gmM90oEgd+zVbMQYggg6OqJYsa/1svrX7oImdlL/+JdGpdqVQo1qLzPOAMnciJZrgn+LIE2W5rZg==,iv:zpNB3Q0Uw2TzkSNUQmQgFcp2lRc1eNqvgm9nBxwgIx4=,tag:Yn7Rx+dxZKIol0mblxP7Xw==,type:str]
    known_hosts: ENC[AES256_GCM,data:J5eeJBVwz2DpMIhlJ4fpcLlYeZlSIBfYkqEelfmDjw9lbJ0H0yiIcqnSzWJTyBq6E7TBYKxUmHtOSWOy4bE18DWCw9GLz3tPa0poIrZRJKW85YHOUFLt6WX/vcwtw2MzbS7wwgxCU3uOdFuxyO3AScc25g5JL7Jypv25DWfaPq9Oir1nJnFknRacl9SLOZypkace/XOw17sGNkIP7QjPCu5I+DALEAvk31kf,iv:WMdUZSxbWXkZLLP1x9QK7q7VJgjVlMVt/pExWQ+dRvE=,tag:YFzsL/aMo8TbrIh/BFI89Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UjEyZUZLMCt1dTRJSlhn
            c2szaDNiYlZhMG45Y2RTQk9SZHZNMVRMMUJzClA3ZTZsTllwSDdHdkdqbUJtc3po
            VUhxU3ZmdEZjTHM5NEkzUWFrMmRvOW8KLS0tIGV3dXc1MHR1eFZsL2RVUHVTRWdX
            MnkrRm4ySlR5NWtRL0l2dS8xMnRtS00KP5dZRnt06/iBgmH6tmYsngVNtWpK/6EV
            IgLpmE8t0hftWvkSUkQ1CsCvHiBKfvIsrDX6hUfUXACB0dbdygNkGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T09:03:45Z"
    mac: ENC[AES256_GCM,data:TQsBGV5eFz7HoeaBIH7ZlVlXK1gqyogVCn4KPbDNu0fG30iCIpKTFhyPufFXQMndJoSBOd0VeMq2Mvsf7zoUjU7rY4SqsDWyf55NBkDw1ETDfVHBa++Dcw7AIZErx167wQ3hIc5oSo49GBVCLEXh0JQxRVhDr6uzBqVE1fJZasw=,iv:jo4v8l/iJF/QoptJ2E23paWRbqGuZ3/TVV4TVzdIxZ8=,tag:wmIrPcG/ov0rKYZFGojAnw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
