apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:deOw5CrkQr0R2H9BdNvSdWjmYetnjj5lAzUaiTIuu3JtveHHZvYcftwkNBC6RCg/kb4fd7cDV4cLNkzpAvh2c1M+nywho4qwfqEMHQccTbedLbLjk3784AE/epwUaRjuyEhWuo0kAjO4m7RYIPO8lcJRXsOJyYNL48HD0jG/27/3WfCkwXKPmaT4dW2OLfRucIEsTtz1ug9DBbnOEiDNz8XLR1r8JuZT7rtFIj8VOmPYtFGbPt0F5dUL+YL2HlfoWUY2dy+I9Ohm9q+63tCywA3V9xzSLic0a+iDgGWdgzlwSMIfG+c8QODO4S5i9NGZHuPqiJvqdogX3p7psk5IFaKz4DOTu007iQuZ6OpQ3CDLt1hU/qQhGGf2yU/VW9IS,iv:LkNCliBtP5vLt4PI5zLtFPN7wR7x4kzR10jpVXCvyLs=,tag:I3Af3S0kkL+2iM+nt/zZWA==,type:str]
    identity.pub: ENC[AES256_GCM,data:xNKhzDGdw/FJyAaDQCoLd+OVR0z3eOLp9omd9IrRtIWmIKwor0P35uXX2wuApmP8tYBAyJ8Of4IpLXkG47qNJSiiKTh2mMxiX1QmSWv/AkqiVDPvFaORx4dNXPlP0dIrbF3cNojky3CW7KXST5Tk0XBFPCcLt0aNH5tyfbC+Lj0gHW0YL9GM+unEk1ByjkqYitvJBVAAljTG4KBOQj0+LkXAl/p+cNaNU0CYCUCxmSgXUPZBFFNbBiJ2MP0xGE8ZFCPYHIZYLKKT0eAcMw==,iv:LX0kAqlTy53+40RBAkvh4CFRrn0BV/YrA6+liL+66zc=,tag:Vg9XKRUltoBNRfQ9zzPlRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:IzemGmCPSlR3rw0Yp0K/AnZ/oO1VhMwKbvBEOpK9GDjevJ4QFwxWO37VYQTl5oDf+xc+LvPJ6H5Yql9dqSWXoGtbdeWpVhJqFZdf+5zqMqiAJGUQX5D+jNQzjqbYfX1sXj18c0GJE1DYROUxWqwIZDd7YaUjR104GYwMbkpiWVwkeMeROC8iQgmL9cK2a/pPP4kLgMgsfAhy/WaPjcOPcBBCksO3CxxzCrTx,iv:TrxFbQKoLE4GtMnpHHQIykj5vywyoiEG3hEjIlRTkvA=,tag:v85+wH7nMq4s4jQ1r7nxVw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z0JGQVhuWW1rMmZGTjVD
            enFPNnBKTy9xY0VvdzVHcm4vU09IM0ZvRnhRClpCSEw1R3V5bFdPR3NPTlB4ZytZ
            Z3RuUUFMVVdjZTgzbWcrUHlySVRLN28KLS0tIC9DS1lncm9VSkhqYndCVFJReVBB
            TUFXdU00cE5neFI4TWtqYzYycGIyWW8KQW7tn3GEiY91RSw4QOwsUzIv+V2B4kDf
            tpzH85fJI/Rd5Vqm5QqAR539daEdxa1qRCA+AsJj0j5qQT7sFP1QQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T12:54:44Z"
    mac: ENC[AES256_GCM,data:X6CZxKhI7bmh3GLFIQOOU/sIBJs/CXAUVClRVAl6ohvMIYfMXAf6FXtITSoq33mEam+PlU1PX8CKrhBDs/U9yqIQkvwjTgNy0X/+uRmkCb4q5z4V//P5lOY3vknQvClqMO3BzYEs4Bpt4I8UpJKswbvJkRpRhWTMtDeVivIToHc=,iv:P+gtWnnZP3M4cnD1mAi6Dy6apHQjg84TSX85BkVaCJE=,tag:RT3A7jrtw07a3RBL2KrEcw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
