apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VWiByR8TxzatmQ9CZOg7M+FjKu1XhtJax+my3PwZ2xALHeWIUm5Aabnv4rshrfvgfPZzZbWVbhSrP1tdkD1/hUAaoihmXG+7Gnl6RncIKcSfJjVJzvBxWNshiif8LbQ5tsB+k6Lv3QXnEdZdiTdGbMoPac1otbpUQCnWe3rbehytwTHIPP60eVZa0tDzYwlr7PpxwpD79OzS0lzfzaqx3N2Hs16/Tzcdsdc89rNvj+521ypTcU68Ax0+iLon1I/gZ+H+XZGs5HewX08B55ypD+jET79lZnaJalt3D+aVPILBYJNT6s0OpozHQUMAJEYGETAKRYRaG9LCvBQoV0lsmir00xYnjB2IGqWy0DHA2tdFSPsd6xSukM+E4aM6NGYa,iv:czW6+rLz6B5jS7jK8TN8yMByouLYPH+g9NMQBt8+Tfk=,tag:C9tke/rtLQGvwww+uqdvqQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:3uM9qk8LnA6LVBpHX+xWKY4GsSIMivk2Y/0RBjFoLxdmZ5ayfOtPgv67es7u/+W0fgf67D3J+kvo/5NEfiOtnAQKdg9q411dXFOl4NsGc/M9aOGY8oLIACZbP5xr0VpOE21HCLHQ0amRRZpZP7W+HYcZKMavBNegVZ5oYRjDFgW7E93i+mqHTTEo5QdAlb8fNDa8d7PmMsMXQbgd4TRMr9UB8toQtPaXWsvESO5Z0izt+uROidMZrNpt6t0Yme2MF4BaGYV8xyo4KJVQ1Q==,iv:O9xrpbWhWpvfVIVCGyFOjekGYE3vpWqGIMd+VU9eOoE=,tag:Cxl6wFba5tGSFlnPlbSxSQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:YUaceqINe+0CdQ+UX/9BjVTYj/NdCi95l8CVoqN8+dTBukz9xOKfzpL7N8CGxBq+lobSAqB9QRhg0nk8StEfp82KdKRCsgK4oHMg3iIEkso0gnjJuOH6LkHFSI+nzrSWwBHoj3EowRu5B3or0gGXiOMz15MEgqSTRfZLhuLsK+33isl/dam6vimLqxTk2cktYbbiQBCkcWgSbWsRw43J/B3HITKhFZz6XUy8,iv:UO54hOrCwx2N2vtAP56yT09Uh3w2JGvp7Mel9qWSHb8=,tag:4h+LDIlW9oi6cgzFaGz7dw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TkI5L3BvZzJ5QjQrOVl0
            MDg1TEdFTDBacXZVcUZ0TVA2ellsVVJyNWljCmNGZVRhTWhDR0tlVHh6RVBVdTFh
            cHoxQVpDTjJONDVIQk1PUWtQcy90VDAKLS0tIEdzaGVuc0ozUW1iQWRNQlJ0MGdZ
            aTlvbk5BekpFMG0rOUhIZTdsczFNTzAKUveon8vzgsNdosnU4JXhjEYrQMz1SsEB
            W4afbzNv0n2K7m1vMGMLT7hkyfgacpqqpYfekoN049PapZ27o3ko8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T12:18:59Z"
    mac: ENC[AES256_GCM,data:CI2fWNklNbjvAQNEfYwRAApwh5kk3OjDt5E0OCytkLK6uTLQPe26ytLLiCE3RSpTMU399afukN5podzVdXsrNHRlAa0JAV/muEhSXKzRyXxIgBbNWDmM4VqGODfcT0gFel4/DyDK9ShWTNx4v3XcYEgnu1iZYhFHJr3ifKNIEz8=,iv:xGHvPgJdqi6TNoXGMIZHwFxQ5smjZPi6Y5Dc7QYV940=,tag:NWNSuMI3F8sTTPXrmL5r0A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
