apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gUa89fzJ15Q+GzefBf/4nPb2nUYdi0a+JZF/VILAaVnJNTweKmZTq5bwwH78h7HImnmwiGi7KbmVRd9hW1nbyDL4ENrEbPeAAim3jpUVFsigQUL7aDU/EuR6emfpRIMQTVErzq5eaS3iUHT44LmrDe0Gta9MzO2Pcp65NfSSW9h8wIO4rv6t+bhS9rpbh7mHwRD7DOIaTfgmLvnbDLJ9uecAsP77ZKLETNWwv2XAvDSNwYNxzwZFNT+IaFQ09VoUMR3RT2GZhi7mBjYBtNCPSzmBBGsXAewtwY9wMT86yrFUcDfhPsZGltqh4+cHATVblZjmERl4OwaubAetkUblqMDNNEzeaFuBJWfdZpJduBzWwlwoNFqOeBN7BY1PcO2Q,iv:JrOjuNeFeZAPVZmNyrywWYbJNvIEVT6g9L1tiFwqQ60=,tag:OVsqg0flWOiV8akSHE/jag==,type:str]
    identity.pub: ENC[AES256_GCM,data:pgwE/PvQuKiT9bw+IzpLlWYSJcOb22KQxWoUlUcAbs2KULzP28YE6ZZM++w6CgVCTvS8cjP9tJtlLWnMm7lR3L1iTiws7GCDf8syXXUyxtgh8IaKPsACBU/RgyRW6GRWk5jxdBBlwEEJbiz3I8lgQn0M4Lu2M9fy6lt0FVSf5KnVLJXULyYj8Lugd2LKjp4opcvF7YdfQuvOexmq1pPDEpZQ2BmnDEYHLraZQ1yBmZobq6BxrA9RY6pRBvTRU3H3gRAV16j3qSIrtZHlZQ==,iv:wGlvjj82kaG1ODpgWUaoT0dL5r+a6TdF0Gu84PS5pIE=,tag:vURvNjniocvQSTMBQnaCAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:E6xfEDoq8RVKQ/cxjqZKTxC0XbYMsxP1v67dYmcmC4uY2OWOVGya8+zNYfa43EwLriPPW5UcmkK1/1PAAfZfm0dWF0Qgpwmy2/JB48UKwmaEv3eplse/ocCSxfcNDyrw3Buk2v30pEcw4PkHWbQ8AiB4Ddx/W5lH+3NM5xGIY4THzTpWyzxE/FsDkcETFNx8yb0vvuhNl5uQilE5i8pVQ6fVjRI77TTbjc4M,iv:pX7LYNw2fv/rwa1mH8qnQJ0Iu2z+DVK65UT1wBhHN6U=,tag:OfXHQqZY5vOX2rjqVRNofg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOWl5Ukg3azJQT0VPOGpq
            YUNQdVc3Q1BTS25vQWhtZVhvOGpJcFdwY2hVCjlkTW5TNXU0bEVQTGV6NEw4czZn
            V3ZpTEZTT2d4MXYzZzJkQ1h2S3F5dVkKLS0tIE40VTBqaTJZMWxrOWtoM3VQWFll
            RlF1WTlNVkR6QjRta3VXYUF5blRQdXMKjD/8r1g/pIJPf7AK22wRXd5ZQC0fw3zg
            XoFNYS7yFN8Kx4lYHHKIM3nxv+Wxr05CjR5S7JBxUYi+j2yggnJtEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:06:19Z"
    mac: ENC[AES256_GCM,data:Ac1GXqOsf1941w39DKOCX96Du1tgPc/2QaEAYqvTlHfVxZhs+jsXLEcIINjgNhvtwzCoglftrpwNzE8VL5W3R7rOac06wdM1FtsSJz+DMC1md/iJf7f14Xx9pbm+03Vb3E8NE92LPSP9XNIC7IoemJtNXXNkND2dZhNZmQnMLvg=,iv:Qi+b4dnZAJA8/HYsgPgturRc4nrfFIeWe1Bpk/7bvFg=,tag:BLMchwrei06faubBhfezPQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
