apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rPJEftIhJuZ6UPzleFZorPM8sLAt1Rnj749ZvtZUkJX8nCfC0lbbHR2ivyeWqVf2p871Qoz2KAOG+4UvruG6SBXD7x/qnGBg/Zr1iK7LihsW2/vGHtAQ0XzZV7A6RQZPma6fOI1LJPgdWd6MUf8+SXlMuCz1i3jRSEF44N36rjNr2LPd7/rTs3ORV92VOTPVbS2o3XHykZNIfMvk1t96mOYfwXQypZKXZWMBOn7lGmfvqrlJZdf2QYiOP8Z/GUz66ZWuh9KTNZaVtpg4GfUfqWG1FOknQ1wfsusOxfsdBy0O1TS6NcxCdvtUG8SGYiknx0dJROGDnZf7IZDNV/5Sff1XTakJ6jVCp15Y0vYLKwtUiq1jIrVDw/dc7VxLuBx9,iv:zam2HThi15Yu/TKT4++zLvQVWaPmNGfRaQvdDSmTlT0=,tag:g9WR/2SMhjWyQiS2EWQq5g==,type:str]
    identity.pub: ENC[AES256_GCM,data:0oZcqXM1GDsb039V2G2bGRw6FN/MNFRmuXvg5wSO2VB0W+yJQFoKRyqmocAOSpFaU7TICfX8mb5NbFSY0jkcfy//bJO3tkW0P/W3y+GG3AXXj+NKUDPwpOYr1fD/olnigjM6Ix1M+ph+Bm3Ysm/LBeutccTp7enf14t9v5xq+hINaBd1jCx4nOEltGxqRzFSw/9xTivlHnq6QpXyArzSxgyxTzCtgqGrGPWVYdobGGBeYUW1e0M5//sXDA5HcAXRMPYynqLpySRY0K53FA==,iv:vAhJDJPoA7i4FROCR83hjIuVtdI/I06U61hGrv5qnzE=,tag:799IKLBrjqHtmK4y9KV89Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:+5yLbmsjUwaTJBXLEPmf+lJgVvy+9vGcSHnG7eTEP5fownp3JI3F9K201h3yXC6Wvsfzrwt60gZi9tXBvt8+b3MZ9W01qCWWIh7C+ahrvblq9QC1roa7dWF7sRLnU7rmEr76JO1FIDkKH037ESa9NNIU2+MDXWAPuhkUnwxVaD99y9eC4cWG+mAU/90oL8/dxfriWYRI1Iu5RIP9QX4No2ygCLQHyS5ZC2sv,iv:Ya+MYidz46APK0prnxko91yD1okADQsIBHK30FVhODM=,tag:LyMPwOnPjKBheb/R3Q61Gw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bnF0czYzczUwYTJoVmN4
            YnVsMENTdzBEZVRoamZsUEh1eWtPUTlpemdNCjYwWkdFNHpWcGxTNjNVTk9rYith
            UUNHWDgzOFhucjF5SjFROWJpdjN5ejQKLS0tIDlvTFM0QVp5QUFJdDYwQjFFeDRF
            dkJubTQxY2tTd3pWZXZpTVpvUDJMS2cKfjrAZab2Vng8B+ogrxXvuNWvy/VuasPH
            ngtubKNh21w1lbq8wzImJpctUt2CYdtIiUAWkHzMctk+sNr3N6M6/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T22:26:17Z"
    mac: ENC[AES256_GCM,data:HeY0OGQe0i0Nave7zMtFgSPatIxXofk6izmeA4vd4+kfdvhuB8xFhzZV31xpGR7EAX2NkPUrv5SU5WJbO3SIPscsMcBLjAExxCq4RTxalgwBnOcyr7ufSkUvQWQ7cJLNQve4s7IufNp3Im9M2/jlTj+fjkmatF1YhIVSxMGo+HE=,iv:0nexrIQaTViZTm9ekpt4iEYTLCMVNdKb7Nhpj2jEIp8=,tag:IzM8k1iEJj0FiqC0pCtQBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
