apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XNOcRTEBamvfAh4HM49w+oCXNHdWesoFhDjXl/SVWSnyLLdwrkgVbknldIT9BLj6DXnI/ztKK/Aghk8BJJO8ZuOJuJjQPzR4eE1kMzBSYldmYnSpRwjwSxLh7LDN8vjvEr0LFsoljuPFu+vjouf7HIpJel8RWBiGET9oW/5vxetigHGTGhvBj+yuRlglLUGKIMwqyKCpzI/K/qYtkCx472kHY6+ND+TYolfi9Uo9xjAJ7fDbZD1godojlraQ3AGfBKovFqMWY1XnCgzlfN3ko8fNnl2BMLMOBlHNJds0GjiqQUQUAP1ygPlqyHMY4DRchIUoSLYcpjFb5Ep1GItmCKwBsTfEOP9CygRXNqdxkKG6cqD9icUlWw7azFnc7Rne,iv:AndTwtmn9LvBbJ17fhA6AyyPZ507gI8M9Y6kkzx+ZLQ=,tag:IcHg/w0mpR8k0ppqUmr39g==,type:str]
    identity.pub: ENC[AES256_GCM,data:7PByvYHMw2KMzEUPdrT2by9jI9CJxQEX3bvDqXADK63OSny/xl5es9bWoqCgjG8ry9iNduD3Smy8WSIkNZN55SBxmuycEE5qF9nA74+PWtp5RZxosoYYGPbGPiLNdBxVcw5so25ltRFKhlOnAWL6X/WsvAdTri2PraaftOvSTIn8xwu01Knu86crBsVleSKYPgUDOpvOo6qjXTvfKmk73miuwwM+i/t6x5RNWbJeyN/L9eNUiMYVJ24aT+wEmxJkn89LkamFUld3iAK+pg==,iv:pGD9XniAav9lbG1LTv3hFIezLrLyQn35/44AVuM9Bqs=,tag:HmXld99tq43wVKw+VoGKCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:c3i4JiXmkU/eKjr3zSE52OIWvRSgTVbR4wpYabqzlogwgn4c3pscU8lseUUv68soTlor07E/hqnTHgNIPWCDYWLglvigIQJrf3D2ByJIascaf3mMNpgRbNf+KGlzFks4Sz4WKGTqVjoXTKsN5w3F8ovd5apY/ysqGSu2TObhlF4RGRACm84tmVsxSLshs1iZpImhaKXZGL3bLhs458ZLIJHhtFTlPijtuQOD,iv:txJdLhtF+zyOWKJgSh9brb1ppEzvA/lRNRs7DSNzuO8=,tag:uxvtwF9gOBqluYy+iWLPig==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWStQa2ZNSEFUcCtweXlp
            TWp5UXdtcjhHS0U3OHlUc25nMjFZbHBiVWx3CjNKQWZhaXVEako5L2VFblIyNTg2
            VFExaHgwSlpTQWZtc3FPVm5rY2taQ2cKLS0tIDNYQy9yakFkZU9FdTEvTGw4dzgv
            RXJTV3JVazhWTWZIcmhiWnZtUUlUVFkKc7TN4sNFg+hXgU+saLF3Dv3BqAZpaoed
            z5YRtQCOl/ey8t84EohFWu33jCaoyJOhDcEyH/g4vuIaTSF2lrCYFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:15:07Z"
    mac: ENC[AES256_GCM,data:oznzc+4pn6TeHGf25q9Xt08dUjoNaMAh7UBfJbfbqUN/At8DI5jH1q4C2bj4uCY3FdlPKnsfcL+EsjM5icftNijltIWYbKZ0shJTw16OJyYG7y9YTE+PNyMnDnGhRcrK/+wShsjTNNGcBlzgENEqUFO1R6RGTHJp+1Nc/xOqtU4=,iv:96eETEQi8R+sdwyDTB2o+5K+ukp3RKUiO0Z03y4Llnk=,tag:lPf92xz5QAjF3G1cnZYSSg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
