apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MnH645bSKgtSEwkCoc7XkoNzkvvVzmkRyXqjLH4Pl0COfy5mVzvJf3JVTZv78F0Q+yc7CnKW9YXRlI1u4r3iObFK20gs2KT+INJaVj9klHIaqSMZQ0bODEKp6LAheo/fXYoJ4vkKcRZbfya6YzEzrsEL2kJFx8ejFQ5b9hYLHQuU6RXWqIJs8lkfXkm8NbVB5JbWSsVEnrhi+8ZirCCI6SEOK3PLKv6SqJ9CQ0Y8Qy1AfZy7bCAN0ESALnzDa+G9B4qrhqtJt9MwnjAr4gxzqETsrQDlIgivX6GYqttvX8tnNCN6/y/r6sDBKjrbMwonmgep1WOex+kB2WlgK0KUjCczG9TxtvOnNSkyiSu9+iGd8pJmzFpu90BNm/ATflT2,iv:iKEZbi6QNgQBkZwOJgaxa8csnM/5tBTMAOY6k8b+0zo=,tag:4ezJL5dGSIVbHB3olQ821w==,type:str]
    identity.pub: ENC[AES256_GCM,data:8MbOGxlHfmvlQDoMpzImdb4MSKOjGG1eTKusF+IyDUJ4jJf2gDv3NcBP/N2wZB7SoMl1G2OpeduJbJSJYhMXZuJba6UvzcviXAQ+3m3UJJ3Cgfm5DorvEFI2yArU0BVPLXReSjC8B14KTlUqoJyo0b1Wip2P+o/dlMxXHnBUj/VnjcYJMasmxwZSlQzVzehA4gHHaEOjb+KGCX0ksvNpYfpsbfpYuE13tn402zjqViWOTjUwiSIWkk+8AZ0Z82Qi/H+vnI6C6YYLrX+GPQ==,iv:sfAdJa3G/f0NXIp/ENcPZQKWH9Z9yrCab2pqXoG71O8=,tag:FiI3UQ+srl/0qYdED7owoQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:35kPkLpA4Amwdqb4ZmYOj1xEK9Kz/b58GdYXRqN5Wyz9lQDyaj5E0SJvJ+ShL9g07FvJtddUzVxqb/XyOng5qxU2V/oPFCzFssdIUBjy3sFI/vzaXS8sIYGnca4kYzW4eVH5nfZr2cLsVRTsAJhLS8jjjk2mVX1KX33JiNfM1OaMCIETMsGvTeUcXIZsX0UcLJJPWCSmRHvs2ogDxCNYQBObLuvyjGmFef6Z,iv:BqjH+4WSo9gSbkWmoBOPuxUrW0Y2Uy1Rx5ycuQrlExw=,tag:tvbLABCFD5X6xAYtpWPTkg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc0ZUQStldjI0cDZja3p5
            SmFkU0pCTjZ6MXRrNmZNbmdFSmxPMGVmUUU0CmtSSWdzWUo3dDFtTS80QjViN1E2
            T1I4OWZxOGVZaEF2cDhLNkxIU0VNbE0KLS0tIEhER2JjbUFHRTV6dk1KdlAwSDRH
            aUlCdlduOUkzdzZWM3BPZDg4TWQwa28K8MHFQi8zMzTeud38lQE1xG2fuh2TAqbb
            ph1EVWb3FPDbj0Nkl5EEcBiBQT3UReh6CG3EZIppwGzlLBwi+2JfQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T18:37:38Z"
    mac: ENC[AES256_GCM,data:AvTWvpT883YansnpE0tUSXVqta5tONYmmWsTnxq7u75MfPShtdzGR8uSgP31oSJvLlNr14joieAelguUQsFT7k1LIzxbgRiFKAJ/Xq9ASUE6zJVU+YF8QrI1vZMyJUjYNL/h7NyGDgp0B7IiMLh+Fvku/Baj3m3yIVdF1Xr+7JU=,iv:skeCXxkTRyEzQsgS7xAF0lZ8CXGgfys7Rs4rUu74gMw=,tag:3gGFyPm92pfDarYyS/2ixg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
