apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tTqLv69QrNxH1SU6bg21u0sPo5kXh/IeLJr2RQXk97IdUY93vXkqGkH8vPXVioG/SvJ2A9DB+nxsF88m+yI/NN2HUQ6F/0HLSUtx8aXhInfEJq9nC11N5ZY0d7aKZIqsBeXYOq4R/iZ9GCysJOieZX8rnXl+8Jn+PHsWHNWuWTb1wf3Nbq+eTsowUSGnKVZ6VRkXf8sGkzpWyPXnnmp4tpQsE0u4LF1xt2JKO73mNDJsZM9RniQDq/HqPjo0Q+tGrDWa6ps4gc8WUDiEabU4GfTmCWue9gEsEZnULqSSfXf3JkNcwn8GSmfJvZUPo6skU+trAxZMN6d6lEkkE08p5zdQaeO90A9C/U3ZsXOvRHWsCBbUCZ0O9sG471GxLTRy,iv:iCABFj+Q4RvTeJGQ880P9vAplFV7nkvUSSHiQ1rqB1E=,tag:nkkd0W7HtTDAFOH0Tcl8dA==,type:str]
    identity.pub: ENC[AES256_GCM,data:1hAICKoURc61lX8/PkqQNginTXKi9hfO+kbTOxSjHCif6ryJQNIHg8kWEMxMKTkBm9U4BlINS1MXdf/VWZhcSv164Q2UaUid4iy8Copc1o7P/QE9dZIasy8HiM7FYJL19kFIOiYcmCloH/qKICbSOulHxK//CSGNLJZBt+O3Wf8K6g9Qfu+9/5BBMu62EnBdieW93z7j/llHjg6FinzbFPZ84TIzW9+0vG/cLNxiRS7bkufHcPQHykqlouVe1tJKyYqBCOfZUer4rzTylQ==,iv:jRBvO1qxD2ruyOtRIBQzduak/vM1EyWZs8HDTYQtBA0=,tag:FvDXrVTZmY2Pqvw8bcfRxQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:rU2y+7r+sPSJxMBruN6fJpSL3VCVpreqn2VCv4UFrd1ySWQSdCp4YcaGgT44wZhzLTQ6xdRepMRNAGCaI5C4okK1m5nPMFsNTpK9PxzKIVssLi7A1zBYmrk+IUowvZzV67xz1KK1InEHbgWXY2TxNuucluF+sTd8QVjk1oPNEVnxBDr6wlrG4UK7/JXhH9URZwCDr62J6F7L79h+in2B7RVmjidJF9BS92nZ,iv:5Go0YY/6CohhLVs2B5Qwsef39K5Vm885k9sTl/pYnas=,tag:WzOcsVgG1iovT6UaUJVWgQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleGxhcnpDaHlFU3c2RnY5
            TE1CUHZPYXUvbDUzNkwxSU9mdGxXVkxvbEJzCjFqa2NDWUdXMHNMS1FtOGZiaW5x
            SEUveDBqVkpHaE0rYmQyTlRwUWV3OGcKLS0tIGlwTGFrMThqbm9ab2NSNkhwcXF4
            U0Y0TCtraS9PYXZNUEZKOUpoWC9wN3MKOsTrM4QUIZl0GwcqEWY4450ojeNua8Vt
            xqsUb/GryigxMFvtBmQUlU5EG98bXpuGxDdsofA2pUkpJCvvYTck3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T12:52:01Z"
    mac: ENC[AES256_GCM,data:vlO4Db/63EVOkNwuxvpXHiWoIkkBc/h2qX0cvVkYGKvg6MAIHp4JfnmByDfVJQTUHPpPTuIqWudyHn68Fk4U04yoBtMm9Fto0SBfrOmRpBNVZEDCAioTu1xbIoGowR1ZsOlmNOhC10q3B5I/xR6BxPEBR6PvZzH5RK0fUFqkxPA=,iv:19tXZEUVjIPCggboXl+kdndSdUYRhnQiQ70Nhpzw3BQ=,tag:2zNtlYxr1BpMnkFz/NZyJg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
