apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:t8kqyrPVZVNjZ4/cdLjL4Y1sXfjzrcYSdIbZSBrrm19ffAvYqu0tr7Z+IbM1F4IAHnIO0eP7krXndt01lo0woTfYSiC9MpMHeE3akamCoyIWEniStNuIZkdfFSjXfJGpETCXGEk8WAaZ9Sej/Eo+NBQ3LRnhWpJ2oyEaqMSXOJ8R+JdGIUPFwFtAyA8LGPz/JJs8M3KVVcf7wz/spMFC7iy7QIAGTgNAUeAI1NV+n0fkeKgwE4hyT+x62hCZ0skQS7+E6yVaS0F9ImOB60Yshms2c0EBJYvJXV5+4hUnz7HhPe8l+iN7zj5K8CYzDZlhh/JarxIC0gCTUlLiJfchMLi5FhfRP54Vn5pcFmehipQOvBO4rMT/0PYyUQlgp1nM,iv:ydYxOoG7I99yISiuqcWxjWHGXGijy79E1uQxYzB1FdA=,tag:SoABLC34LSXseDNCT8TCyQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:j3+h26q38Ka1HD7J8LCvgJrFhMFyWxu6hamvWmk366b9NmZi0iIAW8wTBSP5kuWf0zTn+Jh9f8ovCFLngSk/FcNTPqQXd6Q8YvL3dqAFkN04DEmjm/Uklq2UDct07MKyhA68RvjKt4/vpXo0usKT6uOtw/ZYzzHhoxCVNgUkMmYIk6l3dfCXOdFnkSb5oHvcbKGMgeDuGDtnUZSvAKultKNRR0UE575e81ARhB2OWUbNlImk1Bb8Z58T31ex6qSg7bItVoNT6Wc7UB8wOg==,iv:aRJ9YyVU7s4Yoh91ZfYBl2bzoNqksGMWrGPO5z7n0q0=,tag:HJBweLQ/1Uq1hVuHqXdsFQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ecxm/Tkrx93Lp3WMtbabhSjOdtuDs55r57xWjvSnMzTJ3YoHCIPoohpiK0dhpo2pgOJYkZ+a6rih+I6LoWRL6yrDa/sb0Mz2oRGPqaKkcQvu8+VQBz1psS6qsI/LlO1X1pnTzeIzt97gPmJ4aUb+DtBsfI0Z94fHUY3+PxBAZjECAs0j57V/FzXJwJcIGR9i92Gq7m9SKXcigiV8SFVE5LPV5LambHgVRQMC,iv:ogXGZvaocbd4l2WkM0arcuXVvzzOcPwpvgWU7IO3ulA=,tag:k03Gn5Y9IIvENXjClGv6Jg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbFNNYXd4S1pES1d0blBG
            OXJ5NGxONVRjRUVNOVRFTDFQUVVCa3hhT3lrCjN6TWtFdHVvRHRpdzNiaFZUdkRz
            UFlnb2pWN3gySy9pZlBPak1CVTdQTUEKLS0tIFhkN1VrNURJTFQwU2N6OTVzSTlu
            Y0lDejdHZWZMdFh5SFpoZnlLMWk5YWsK/OV7/2PM4WTXiY7vnDCcDYFaTGgbKLbE
            Bf3HEAbhiFBfBAgimpWCEgIZ+lptFTU98i5sGoIhyp2+bUN/HZcDsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T13:04:17Z"
    mac: ENC[AES256_GCM,data:lkdOlQTWtW9IPNl/SNVjAVMBj8d9vL6W0klhEG+Ar2L7bTioTLEOrDFKt0LQwEKiz0OTPddbv5u5wtPOKh90v1nvxWlK35dYA5Lc1fQngOv+L0KnwWa+xg6uLyOZ3A/6c6bXDd1rJd+j61nPTsRe6XeFtY61RKmP1ZcW9/ktSIc=,iv:Kw9Loctw+bJoOf6XHgJdcVO6JYNSPh7EQLgCBftVnTM=,tag:m6TMl0sPiUBmrXvExzX0Sw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
