apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CQd7OC7paTkeyk4GVYuRv2TkouAR/s5h6BEd8ife3be3aGwMeKaBYXjxlHGGhrGpNcPdNDSdnKTZ1EV5qZGzF0wwGT37g2oA+1uF0BHGhVKMd5LzkQBxBnr4cODoD2U/seX2ETNpuSzH+DSSCaILTLzzc/7C0cCcWm1mB+CkrxRUX+hk2E41q5SeZbMeQFfNjCxCpXIxuZy6M/tB7CCufV15SxwKfv6LsLOFyax3olG3a6f7JIStGsT+0s/rbs1BWdnCrmIuaKUkorSyxxYKJxMJLQPPU0VictpGBnYKR5q966SiekTdChOFkKgqoXLqty5VdrOpgwW+ujrBsHaJ7cgdScA8sTs+zkFPZdqu6lkXiVr3dueQb4KQgtxkhyMG,iv:vsKVcWh7nrYnqH9UVYtcIQyS35KEkAA9Qmw8cruHMLY=,tag:xtnUYUhMZQzfXVPK5VgNiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ct6Jx6uZ/yfHBvQ3/3+ZprzSYVKUdM3el3/3zZd+VEUMM9/HLZc69k3pdxQDw+SsWNDACp7pWxcSMYMrQ+gFjOBbIFj9RXzUqflGybeR1h4QhOWift8TNlq0HWUtWMd3hSZtwwHw2Ts/dL3aeI6ViZfxFVHntEtmBfQDdTA34YAjPexZM5vWG+qlxISt/ndQzHCNikuhglQ6zT83fYekzJ2ZscfWEwWTg78AvUTgw0giDlcSrTYoHnPlerpb2i4mZAjkKtYHJMO15VKHrQ==,iv:2rg/KfkLt+4VLA1a2RNDqYmOFD1oYV2YMfh8RpVyMLQ=,tag:BD3NUBU0xqt5Mq7LOjc0cQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:V/OvTquUNQTTotrnGu+nmCLgOMKtw2qcdlprjI23KOqiWSju6ZiftptvTK1QoGH8FhN6aUQNRHDti/Pb6pgl8Tz+OLmfczBTpBezg7R5ufXak+KJMl20DKkBkbPgWhBHUI2YOmCo7d0A9mGd0bQGpvrplynFhJGSZU1iNyA8WpIWDSOmOzTy1rBGhedzpFaSLEI1HOFHobWUWXwqMTZIAv95XeIUPSDDEMvQ,iv:2wSvhgyvM0xaTvUdlWeyvm8AN8hxg/EzHmI12CBT36U=,tag:ZjmIqX14iDejUpY0JHSW8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTXpXMkRxMisxaGQ0N1RD
            UGxUb0ttb01XUzVTeTRVNTlBaHN0c2c2LzJrCjV5ZXFUNi9XSUJFZGlicUFIdzJP
            d0VhajFzb01IUStJczgrcE5RTDZWYmMKLS0tIDFJT0pqWjJBY1I1RGRyeWtkWEhY
            aU84QldDMHh2NUtyTnRlYmwrcGVMSUUK1J1uGdSf27omArBdCnRJigq7j8/ZLoK9
            YCLmRi6LFUVfgHtPus8amtIDF6ik6/IGqDemioC149Y5u0jpt+s3ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:16:51Z"
    mac: ENC[AES256_GCM,data:ktpUG0Nqz7r2gvgewRrpWWXqpJhqS5ggAG6ij4KauqV8IFkXFOge9Ou2vkhjzwqKU9+o+m4rIGiJXYraSj6y3errQE4OJhE92i0NVO92+bbRSIVsTecLRS03XMethQr8bx1F0sH7HF6SQx8+J8hydwc9FNMXcQfOZ1yjJ2bxUxQ=,iv:HZVs8YwCwJvu5Q3YUPR4AIugTfzyW8WzIMZ/xWBU8I8=,tag:Lgrw6+CuMcAgdDT2+WiLGg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
