apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:D5jnnuE1XvAqfJGu+Ihcxd8mJzBwkiomXrpSSPuHUYwPXeH9BNyqI535IenxZYcuXaycWJIqd4smraZO+baEIR9yAYgPBMgIV8ipK9AhmL+RjGecn4qjezlBVGq9tE7rY2ehubgg4LgykExLcfvHvV0kyH/QSKICGFdOObHBQ9jUhs2fuP9nqgFE3yzAAeCpVdssaPmBiCFJQYMla3C/pb3H1haybZGj2geVO6cvb/W6uwgVSHDw94BzRRL9oMPnM63b+JcOjFd8+84znkIyMXoPLlGKXzOf//c0eZOcW2q8sbXw6FhqFeopXZXgRXBl7fHtErNdfFRn5uknhAM3zL2oY35fBf46aMjIxl6seXxPuGpRdUIwyX38RE4VcaOg,iv:rABtM06W98wlI+e4TtoXjb+WppkAH5ZgBWWlncgOhyg=,tag:qDnwOcYWc7goBKCBTmnT6w==,type:str]
    identity.pub: ENC[AES256_GCM,data:UaYpCHn8IIemECMECXLapDdFJugZcs1XAux2igxIPRuwrHv0qUxGLVDwb81hVlRluiWy12VUtdh9IDEMg2mabCCWYnrYyE9MZpxfVs36IvovE6Oahz7LkeXLhICh3fWtdLOderfm/C7ZDkggTr62ANSedHPpyaFPt3USX5AO4SXzSyw3wFTNIlwzHgMrEq55UwTI7MDAdkZQFwVhYGYFEPyf4T8EEf+3/HnKAxW0b5sHtjDwfjX6bAbIc1/gz7qKAutbfdYBQHRCVBfWhQ==,iv:UJtnGvRobz3aOB9YAwBEvKcwYyATAdXsvip6A87Ghgc=,tag:UloKg52Api78MrbbZWjm6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:8rNmQKXNBWpR3lJuYuYgZSK3cC8rM1mro+vk6erbFhoH9FvNGOt58W8spbUPrihk7mg4ZU+VLLpD2v+iqvzu8cQAOxaccIrNRLOrUGaBL3FvocYJo3ZiNLBGCxxL3QgrZ03HwbT24h82CBZYuzGxhJmSYoi8NaTwm4x05B5Gn6qIUxbLOwnTia4P1g+T9VdLl4c/J/vb6LtE0TdIUP41tmSQHMhrooa8PAMH,iv:LtqAQjxtMEel8iX8QtcBTYqhkH2tAeY1saX2punm9V4=,tag:5B2ql14N8paQ1gdE1ftkZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbFAwUTVYajFtV3lKYlBy
            ellsVHd5ZzVQbWNIOFduRGN6dFZ0MGF0MGlVCmpVM0t0Z1gxZzVOYnBGMXJOQmdH
            bU1UY09jT0NOYVQ5S2hPeW1GWHEwVGsKLS0tIGJMTytYVGR0cTZLeG43SHBXRXdw
            QnN5WVgrai9CQnA4QzNacUdacUxFNWsKKahTzVv8WyytoDZnwvQC9P8WhhF2LDrX
            UgcY5tOmGChtIXzJt8Wu+GCqI7G8iWhwhQSLyFyu9WtA6wRzJ26snQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T12:12:53Z"
    mac: ENC[AES256_GCM,data:RCuyNRcAZKQJGcwj4zgo/JxYAHFrV8iRItpmB+XmnV3CEdV+g6jNnVkPv4pCvexG6m6f7AflJOsrNbDTzzehAk3DdsWwmZUAYzXXiV72XjPS18bA0zVkb/uWKdKSWQesdt7JUrQTTEJavN8r8yUSzzl9BRDi1OtKpV4Wrn9DpO4=,iv:bHrRW6QPyulmDW3iv2wO2Nv4JQD6s1z5riQj63NA2dI=,tag:zkHPEQRI52+b6xWiDHUzEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
