apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gLRMV6/zqrQoK4IG6qTBzfRXJHsBWoqYGj9l2rQPE31LjJb6/rK+ImLAA4wgGkG5sLfNKqqvzWTS/fOflnQ6hLBXpU5kP5pX2KK11PiThuDUWenej5QYxAuuSUQoEGfwaG0uqnpnTGBh8SdEZEoNtcMGDKN9F0daYP79sNg9fDGtteDEFUa6aE7o+gwuFWpxHf7Y9Yt8fpUQBZdGc+EIYuUikJ0FJhRxDkks7BiFmm2Ro4YiLZipj6x2YFgigQUl9lH14CGWJ77wdETtMQv+yPKMWr5Cau37juve4NsegA3DsEnct3m0V6NJ4gLQ9nShlSfPk1iDOqbPMN7my1diJsf2hLYfdK8ahOHa44fgBR+2cbQLPhdwvkvyaWDfU5XB,iv:aIfa5UKUp6kFRN7+eLy/lSz1a7sdK8zuzI7Zz9WFcpo=,tag:fkYmebvQzNJG9HCN9owlWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ya7XP3JRpwZTweOENF9aicl9Sn5KwSOpSjMO9IAyf9kcL732JMZyVEKSeGbVaZ6qlMPqX3kWbJbdaFkVeU6hNv09DA9hl9xoep5CvOlBzuWO47JfQGJcsbvvWin27e/LGJLZheqS/5Cu9q+oQ9RZYWA5XEkXNqm9gW9hQ3DLV6OD9t+V+OSYb4cghPoychyfPicvIl42Ws0LWSpckaaHLiCDARDgPTApCK0ZSrTHFhMoSu67UiafPxVlxElvqy6kKjJwJCP2zI92ohtxTg==,iv:sB13Cv6JZK0g3imENkfFMTcGP/6z2cSms51xWYtnlUo=,tag:lwGQ2aqWYhgfmX/iQVpotw==,type:str]
    known_hosts: ENC[AES256_GCM,data:IgcCliYiPeJyrDiQJ8tjB8lTdKR8khmGwXz9P1vjNoq0EG6DGcVRb4jHSX87Jwmbujpd9DnLnqMwCZl6/onLgwYo88OxsLlqxjky2e60zBd4hSUcNiEu+aaTN1NW7rhU+ut6jpJM4B5Se5qTZsm6zFk6x4EqGzuJrFfCTnJ95A4d48b3C0l4Ajox5ZkmWgaPisJ08HE6CqvAHwXPa3cll+Wv58XqtQVMy01n,iv:xPv2V114FJJjTdaem1D1GA1NbhwnODHdfaycJ0xuf70=,tag:elth55LlM9HjHRuZMnteNg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaWZNSnY5Z2hMU05Kc3Y5
            NkhIaGhtTGxHMEVNVWlITXdPS3F6Q2FLaFJ3CklUSmNRN3FlWW1nWHhyWE9pTURi
            bGtsRVRWbHR3RVVaNEc1TFd1ajJXMUUKLS0tIEJob2lXU1d4Mm9NV21Ramw4WUJn
            ZUg1eGhQaHQ1Q1BMdExTU1FzZ0RhcVEKgBHKk4uvaP64D9iHPjuaGUgo2IDrCHa9
            jRu2j4h8575uyEFE6L13JHj0M/oKf/Kiycnno3a87Csm8thhgE6RXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:14:22Z"
    mac: ENC[AES256_GCM,data:Uhw5xaXmp4r0PLAki4nDKH6z4M0WUzHhXzy7sViFSRLDkrvN2rx5Wvqv79RLu0QBwFK6JgVgiV0o3IaCiKFf3ZlJzHtMLDxmHtTc4guqAOJW1xEDYxNFqdqQ5c63YfOdwVPR1hwFJqPjsuAOQ0UFgIQv+P3fPA9NXU3o93Grsvo=,iv:2BfUorkeP7lpr5Z/C1TA5LGWbxi9C7AnHvpWxPbTiWs=,tag:f/af308i4+XWYiwj0bNapA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
