apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sUskqlNz2ZCXEZYU75mVrCbi85BWvCeUet9PerXLDwNrivwR0d67mmTr7MSMSeWDESKGKGLGsEq8XGsimTST2HKBXv4H+JssSLkn/kgqQ2B0qbRmzKc4cQNO25CGoP3MbbkcSGGUt163eL0PhhXauL0AgLnCSOLZA6UYZ7dlD0keUSSei5pQZzF39TZg3b+ncp4dZIM0tl53FSA3yFpGfB5xhEoOLe5/72akuuN+FDSnH/X5h/tWy3uO+qpDy4TaHlaDqv4fAy4BWImwfm8OPrDeqTPrmYhqkXhmupDC+8RCluSGDdrNyCPEUkiIb99z6NmZclGnZRiGrYH3EBrkeomLlaQLKemTrwSWaviO3niIxCiyX/HXeWu8nqiO+j9Q,iv:y4qmh0uyj7F0gmR8uzD1IIIJDx8YQLkuSoAxes98Ito=,tag:eHZhf+FwA/w0fitWvkKi8Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:k0WvLfBJLsEaxGcCSuXtZf0vTBwCMYwcKIXsjVRq0ztH2j8NmZi+23ul6KzaLEhGP4NJzBNoZGf/AVRr0D/dRu0uwr+nnHeFv6BPe7ytlgQ8uXmiaSVDdaV3D5w0iADyF2n2pov8ik3HWa3Jg5pU92RFhROz3LI7GYxjUD3UO92IM8Wk5HAvZHl0YzgHo6vCLywLE3GHgEzNnwd5ak5+46DdID8RwhocajCWbtb3Ej9STzccow3qMdIIwpkIxq3QCj2EFLX1/UbHTRtKJw==,iv:ToAE2g2Z0RhRpU/zr0gKJBkCfq6tlgdhQpVJBAE6DL4=,tag:48T+o4MhedDQPK88xr46lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BO4zpxpsfsg6Du+jh8YFqz+qpuE6hQ1MWTz8+Ro0KBGDGE5VC5DdUBEKIo6xJVH8QfVoZHqz1XEiqd24C/J+zsTkDwFOe2OV85YXRH+rc6wuwTYlbQxrPy84g7hS+T41L2rpsD7R0NNsDtKirOtAP/C6nDfR9RG+uG7jfvS4OTCSXzzT3DF7nqzXHpDMd9Pr9lQMPbQB6CgbdnY/uS552Bf5q/tIvH7H2dLQ,iv:frxGA7Va3BYCTS0Cl2QeaSRjqCvX29rX0i/fjmDF2+A=,tag:uUchduRK6zCg4i8QpB36XQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TnRkbTNFTU9zdi9wV291
            SUdmNGRNTmhGRmxEYWw2N21SdnBHK25vU2xZCkg4cVZPNHU5RFNNU3F4a1BvUWYy
            dEhiL3FDeUk0NERIaGZ0dlkvd1pXZDAKLS0tIDhNT25FZXFyUzB4UWRKbzNLNkhz
            ZDVxYnFHdHJEcVBaeC8rb2JNTklJTU0KTgVNlInQ0AIoVmY689hVhc8rE1S8NbHe
            s54FN12q2X9adIcrXTyxt55lYYg9iR2t0nmnz1Q93sSzX3xwJRRcyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:36:13Z"
    mac: ENC[AES256_GCM,data:/kbwz2Solza1Zbg0/B+slhGboqAdFyE3spEsnjMZ+d92b2YpX3nLL7De1CHOusNIKG8lBwUlVcJgtEzNvM909xLv7ImCHURJORE5YN1ZdLCIT8u3q4Fs0KI+6GJ7JEmFZdLwx+YUJWhPnkUm8dDuxfnpoT3IyEEbtOqehlR+zNA=,iv:7MQORtoPFlQqZ+OiDJXK3cFun+iqQ80CNi/JpgcDgA4=,tag:OJ17chDqjlQgw8qEf/KKFQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
