apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xsAbxroUXftC+FbJ28hdchUVEFbFu/jVB9RCj96EQzveTV3gjjYujOtObAbf20BeUafCJ428dxbN/SdA2RdJoyDXt2nO1LztdBcXfFWbijoSt4pR3X2eoRmDvcCO2kJBTMw/gccCW8STSpDID8/vZpB0ZXxXu3Bzs5iTYvsQgcVySLabkvF1gULNVUN+8fdmD5J52SCcg2dA2uOCcK+zvw7Pq9M/FDyomZiNhfjUXT4Q43M2t22xTa6aDCVGPy6NF6EvyR+gO6YU+lqxRSYgo3Bmtp9YME2b8kjSj/J6CvABb5NftUiCL5h2qz8x7xb2J5/zaSr0+255CbAemje9vh7KLrNwKDkek7xN7CPeSRKl2zRczdKNYuSuIUAdwZnZ,iv:ebC5F8BEQ7f6PH1f78GU2IDf/B6V9uZvOZN/+LUTHZg=,tag:lx4/vAaTc0tXVA6rgop+hQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:tv5iAsxraFeG70TTgqa9XcwIwL6p66h+d+3/DqQp+W/xVfWS45cMtqxhyP1k0P3uTSvDtWsnQ6kbLX0bi+pUZU2AqzxbjqGzl0+LpHMUf++zmX7i3TehP+ZZo31F3SBv+peVU3iuitRu0IHgjf1mOrXWzrKZARz+R8F9wNkitRmDQc2orWFafTV1AVpmS1etuNc3CGSF4AWRVG43DZq/Yyt9mqHDktfaTSJtviz2ZLcivP9xCkRiY1ig02XlP810wQD9mFCpaNvliS+gGA==,iv:07JtvmIPsUdo6fTrFOwVcXg9Q5Yq2j3V6olg3xk2GRI=,tag:KBovnVarb/pwTTQtpDmsgA==,type:str]
    known_hosts: ENC[AES256_GCM,data:kRJFZEtVuB78ASlJ9Q8bN7KBXj7RYRaiUsPD10RfqQQ4pgbKhczvONB7oQe4vtkNS1yc4JQuHz47cZBWW43jN2UoRu5pS0SUZODhjFJo6G88q3uJUsnp8XH+eKOak62jYULDGqV7A1r3ItOdzJT/djgsZ0eIbtydbMgeu/e4F4UdwmTh1N8ae0CN36L7qwvVxJBzzjQ4IistyHM3KTQupelV2imYnKfHpNCQ,iv:XuKp3+TGkO/aORStoAnaa48+zcHPDSHL786h8HCL/y8=,tag:lwaFQXN+slEhFodhmrymVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SWhQY1ArOXYwK3J2dFlI
            MXB6Z2Z5bjkwa05VdUlZMzVUNGwwUDRNNUVjCnc5NDI5YTZoMlBjbzF3cVVuV3Br
            bkc1TlA5OG1RY0RiYkRaN2hxZnJqK2cKLS0tIEd0em5qbTJOOTdmT2U1RnlvZVQz
            Ukc2a1dRaWpBdjR6bzVRVzRlUFRXc3MKlMMv5azr7KeyNBARq/cRNGg3kzlMZI6S
            7Sh/IY8GkrTL43oHsCQ1IYDWskLiUp5tH8q1NYJWuDqk9OfV7PZTrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:19:57Z"
    mac: ENC[AES256_GCM,data:6BQvVn4jynTrifPN2D8M3bQV33RJy5KmA3vBGhss8QzVmfeK05Hqv9m3OsgG0fqRRFR8f+Gb/MuRZ4evHxZQ+TVGtoK8Pt4X6RqlT9yPPaqPREF26s38lWYy6aMa5aLG0kNYekV9gY2O6yoKSndX/yaafMry6btB2AG4zlHe8P0=,iv:wbv1xIARNTPD78UHGQpvijeq/otkvwCqrjAx6bA1mcQ=,tag:5ouqQedN6iRY0VAiuBzj1g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
