apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gW6btANrCXCbWJFgC+f+9X3MHM0jJb5J+bRUaDjaNqHcMXI50v4IKPsJSXxSyYJrEp6uRtUdlguWRvOLZyUEpTQqJFIWIcp2GH6Bntd8wEJMdWjXJ4k5uLAlReq2sUa/3w3IvZoWuSkLQeGywjFDcJcjiyHxpj09URhjs3QQJDPYmnx4+26yrx6LBwTxnoSVpDML1q4yA/5hEl1C6bdn0LSpkskqu/j8mUuQQ+SIkM+lMfejkPkM6Em5AUH0uX3AKy5kZOcUYIGYz2O1hlW51dgzAcSASHHwBM4GGhC/D9NZl50eER0TyLgVT5DcToQv29IqJ7S9PjSVdHBD4HdA+cii82iVWr/I44h2T28bLpgwzlgOrEByjEFtL/5CxdO8,iv:G2h1rYTV7Nb5rbkEwbFy3RUztbR9WriKSEbFnTK2kds=,tag:R18Bg+UkW0xQeq0lcrgw3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:hOKTMaP6rFVJwyu7Q1S3hqbi+qaXwooIYumL1dmXj9jp9doP/vrtii4n1GfQ5qAc7BdUHwXHkQBWTuaMAemS19/7hxtPMrtrKvi8mq+Dwd6ZKhK39UTdOC4xV2gvKNUhojaoDjXliWM43Qa0g04OGpyCxArd9EUnpx0oHLrwfV6o2OmXugzGchgF8q8nuPlrpurNVDerDWBE+VuY/2L02oT6CAEoHvsc/mfiCeL9l/FZeA0DtYe0CSUxVwdp0P85MWMbI7tOx9nRNyCcVQ==,iv:w9a0qqgvut+kPwkZ280P7/gnlGbMSa2+Tw+zU555I1c=,tag:007dqvxuqEJ7IO39wXQmuw==,type:str]
    known_hosts: ENC[AES256_GCM,data:cIR2LHMH1qapV5M68bLzzRnXkISlnOz+KXuYISbgPWc2u+QdGGk5JgN54WRH62NP5B0Bs9EHo5Y6tdzwEb91skV96cnSPNOEQSjBuBPDgD8UDDUsV1IZ6nN3FySPbTEceFQVJouQ/Tzu9NEgkxbjgqybeW0LUx3wVaMsF2r7wusXtm4r4GQrx612ZoRiuzOKIJ+Y0ocOmHCDYbfJhedss/sRp+8fUV+PeVsZ,iv:6UCL+1mFXtcyHEC1j2mF/9qWb/95rhbXi3IyyJHMkJ0=,tag:8NqvJkG1tqdJ/FFmFhNNHQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL21BZXpsWG5uZVB4OVdh
            dW0xTkc2aTBxN2VBbDU5OWM0L0UyK3lISVRrCmlxSjR6d0laT05BQzRIdFV6Rk1u
            OG1haW5LTitwSzVpeHhrTGRCYjRhU28KLS0tIEt2azZab1d3ZDhUUzZiZCs4RHBo
            OUVYcGFPVFlLeXlkMW11Z3hQZ1hVNUEKbt9A26fsBVpRwaIt3E9HzvWVq+Lug6AU
            v1YOJXKf0V5J1Pjo/Sb8pSol2TxFYhrYS+hfbPcr7e+y5TRsa6m9DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:19:41Z"
    mac: ENC[AES256_GCM,data:W8hXR31yv2ZDBbPta1hPsa2tG1F5BGob/gg0XSzjYxSkgQPUgBtaDb5B7ZahqQWLP1PfknMRrjQMo/hNQvuN3myxTAwk+5Em9VBZU082TTJ53mPy9rsGjrlx8kjBWwWrWW998UVMc3oAbRbmoAo/MYB1yo94R4vnHOlajSs+GMM=,iv:0EHJtsIYp6MITHqKcs9mvBRzrO/VopGOl/U0Vzy8ir0=,tag:a22Qj3k8fr1aMfo9TpcrNA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
