apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QvZOeeAdw1nxhCglop6N+yLYZu34DO/Addnnz4PVUUihXdcpstNtxzoIZ8O2yTnL93Y9X/czMPSZt8WDQPMipkIxQsS0u46buAO7r7zXlfUWXmAx6V3I+qIDdR//Xzm/gmu90d98NXbX3kOiIK6vtQioFPfh59/31TIliCDOcZKHq+RbGSJyzq84e+NBvevTP2fzaiNmkC2BB9YDqsgOj+UbZZxZnKj/IhKmBazDRbJDq7oXgfj0eb7ZUqTopxI7APwk7O9UEXCMtnpfVLQJ4l7QTp9qYE+y9JYm5mSg6Un0wK7XK+UJXoicShDRlhlu4SMkHLjsby5uFad/DfVCqAckKWC+FCmU//6M4X76R1vOUgeIWPzwXwV22Djp3+8l,iv:FdZuwWuuhQzun1Q54pzdOBPa2I01G/oRFrYiKtLCcJw=,tag:MseJUq46akn+DTBUOX+8Uw==,type:str]
    identity.pub: ENC[AES256_GCM,data:3vMajLKWOBlVSoy6mfVQSikkc20OsObhjX3qM2sAz+2mvjkF/NAwbWDrnl73H9D3iB7NG/BrKzX2HmkfjL4fPRL6WlGYYjR+zZQy3PZFTMcRT+7lS6bjAQxw3jwRXGI3vM47cGxIFTaRWUGttwh9MQI8zPo6ava8anKFXDeQQbRuQFIvPCGOUigEvpPQHonvHShxSMqjeeXwUqUIbZeH2mfun/YwJ1jNgOPVV1Tnhq8NgcloDAEGO8ythOuLQmC0V8GBnV5fX1xAUa5DBQ==,iv:TJm8T9ig14zdhh9rLTBOOe6hCS71DQi46QPWm+4MPgw=,tag:h25Vrm/Y6DaZq7935p++OQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nhmjwsa4k8dWq86lvIlZebuR8hOxiy2Er+0KDQdPg+FSLswkMNJ8ktttCRs4Apo4DTjiLEITQl1Ne25G9Skx/QAFQTI+Zzl2FxhqkbF/xZ7VlwWbpsNbYeoW2oXCFanXQZ/pjr8XjmxsXtbnbCzoVUeAENI3spKPR9v0P4Ad0geiV9G0l/UnKYs6WU9AI+C9z0iqxuZLk3BJDCPWRjIdCHvhZXAMvbJtlVQj,iv:n6MHTzySCcIH8q3wTRcsRroHP9t48wR364ViwKmrnm0=,tag:bKG5oXPf2HS8xmfp/t1mfA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRnVwNXJrZ0pqQjcwQjVa
            cktCMXNqRTRNeENabmlKRjZaaDNYOCtFUjJjCnBnV3hCcmYxN0ZtcXFSYUpWN0FY
            SVJqUmhLbTdXcThtTWFhaTNRdHZ4V28KLS0tIFd3TnY3QytYc2V5a1VZcHR6MUxt
            ZzJsVytaYTV6U29Fd1JIUExSenZjYTQKs/r5wNkxXcVmTP+cXSMeepNU+HE2qmAq
            1eBkAdKBDn/bqKZVqUQm86DqD2SvpfVDOuP/YidrKVuexS2YxeNuKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:35:22Z"
    mac: ENC[AES256_GCM,data:XK8pVRnKzGjAWzLm6tkfQEV81nDCv7Zq+sCillzyrnUjkvJETe2rMeOxu9bGpXYcmO0wGu5F6UHRhLK+08WeCpMDc2+ZVcq4jfIzCJfalMGueL7eL5LepBsNS5CQs4eSQFhw3tkF5rtAPE/1nivzxQkqBKMaPBknEa2RFfv823U=,iv:PdwgrI3Uxp9lR7KhNcUSzlZamVzWFVUNeYf+bFxSaDk=,tag:ZHdWsgFugis57pvBHP86WA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
