apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2BKT+7HOlzDD+F3W9dKh18JJBzz39C39ToWTxdUKmUMkFeapP25Z+XINucyBfmSp1diqc/S/IhBox5t1EJnUBdY2t6YLIm7w7CDTur8uF/esYHU4/LL6eQCUdt7GTm2tjgjdapRAMVpfBY8TBp2zQ8vbn9TDArIx3mOGPNJ3haemn3tDO72CsOeAne1n3onBa34kThSjoRsvkw7O65MY4//w2dOYA9/RIS957HYHPBBj97Iio0TQhT1sg7qP9h3aFJQmIXGgTl7/fRaUYvzeorzJJzE/0x9BK0fuf+3+VULfe1Zw886WKTH2YoycvSwdNEd73ljCnzGoC25Alj6rsY93+jsxCwzRHy8ZsSHZJjeL2zzyzQtdHP3lGoN5Lxcb,iv:sZLcWEuwc22zTeD9KlOrPKFJ1tMecxMJEv434t8z8BA=,tag:V1VgAkpcEAcx3sJQALLujA==,type:str]
    identity.pub: ENC[AES256_GCM,data:BEGpKLmJ5ObnGtDyjWkvOBZcuwrfmiJI44WIxD59eYY+9BpBNYVZvCsgQ9osJzbuW6JVsYgaYXTDLLh2THcJqOpk69I7EnCisjgb4cfB3ufTaSHitITnOirxUEGnvIrwd3gHgtkB53N4fjfLq0x4573QzQmH3Nh9IGjkObqXrnpbyf4ZuRSrIQ/ECC48xyjCK+IRqftiy7VayXRVkUOnsmPToXbB+dN50ARdmRlLgM1sxv6eIk1auIZkwpjTzVM8dhzgeHmNvWhK0NMpnA==,iv:e67Bns4LE77xfvhrIG/DyyKT5CPW6ad3bULB2vuzSWU=,tag://MS7v557hxsiHxCuEyiyg==,type:str]
    known_hosts: ENC[AES256_GCM,data:REpOJNdGJb4rdp3j5oR1V4jO+eBn7woqk4AQJgFpZyryJ+p4yeza1UrIj0GSq/XOtLlVaptUp3uVDXKl1vT0W7Ca5JMfHuW/Yh/D1jGen5KxqfIgY8Jq3mfpYRkzYFsCgNrKzdLQqPn/sPfal9ronsvz30261SuDLYXf6S0Mw5WsbN/H5ZC1b0xXk9XCdsRREos5JnpI/rqasLBc49jAH3u0xj8Ba37agA17,iv:XRUROb9BDbOASBAGE0eHO/WErYSjJQ+EoTZKCa3wIw4=,tag:oPUpx6TsgXdmL3+tskRTpg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcWpVT2tEZmQ3c3VHcFI1
            aW1aQlIyZThvdHdic3lEc2YvaGVMMklnVWx3Ckx0OGp0dDY0MWdOdmwvaDZLaVBw
            UDl3dEtJRStDb0tSaTdac2tTTEZ4SEEKLS0tIFpGUndXMWVkWTlKL1FRZWIxK281
            WEtHMEgwSTRyL3lGZEd0REdhcGFHRFUKuFA9dJ3qzEzxwFRVdFX68Y3lxa+6gVw1
            l8WLsWbTxmPj8SWs28ueSlBxM1GHKMAnicSMTpANBZZVe7Aov10iqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:58:27Z"
    mac: ENC[AES256_GCM,data:qySIUo8PYrBXfxZVVg+AOH6LqLMH02b/rMkpSZLV8U5znXSvovKEz1o6DoS5d65LZqjSZB38rUvUpXgQ0sr46pAwC5sBMwjgstaVnxEo2cFZRCQ0+3Odx/lNbB/+FvknU/WKIeiaSZfc9iMp6rhMXKfxxamWWMFDjs9eaDYxAXo=,iv:x0cbyJT9+WL0t4c/iN6ePKJoNPMzZCRByhK+e4HqsOA=,tag:nglzKUsofXwRriL6Of5dXw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
