apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aUt8k7sa4R0umZElqsYePG/oW/deyjabqKa1FKd7DZ4MwBTvu9xtumANh0aALz1po9QT88TQ4/aVWyLgeBKilNWrjs8mexI3ySSzg88+OL/Obb2rrEhxVnVJQuxjrFERbetTBfK8xppatqQNsMCPsLpj5OZXUZdbwxa07ncxsP2fJAaBPOTdiMFya9jGidH65j1wJWmId57J3LmVGvSOEcMHxc+uZa+8AzkC50yfH0b0bjm/mpWRdzumBlm89JUy+kQYLjyGvKZZaOqX+fdaF4xPrGWpI9yIj/Tq/wc7aOkYYVpFWoPQuCEaoZ2DX3EtrnJtsxOoACktMAhhtLnLdJQyMvEyCTi3eAx9047hc5OwbnofX1a0uEEr7bAlvz10,iv:jlfQgvRwL/ONZgC2Sk0B78RRntrOrBbV5xXvNeb7i18=,tag:vYOQ+8PJn/hw+EQr888WQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:GL07AIwNQ02vetO26stdidhCn/n1I86/MnIm1OrSdQW19wpwjnZH/BWhzvYIGySFWzTJvER7N4CtpZ06g1uW8dIlcIBJxOz4mQxDzrjOZjBW8d7WsFD3cM1OPeNOPf+tPx9udNRchISTWVI5pdtWzInrXWU/050rAvAbM4ki+QBKXBdPVgb57yVI74/1jPM8U5ZuGIrL9f/Po68Lkx4NsSy2LHJAsqN76xF7Pj7voIestycuK6ta2E91iqPcmaJIu/sdZCMsN42VNNNwew==,iv:a3rGXvLBElxF0lmWNQ6bBiU2HExG7DCkDhxvsz0ZRaM=,tag:5vK4RINoFGW9daOF+Ig0oA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8l+gcd1Gb3vJb3SbGeDesQEQk1++4qPQyyO/GClPpM6DVhOo6qFCRIDyLkFv0B/8DqgrXguJi66bbpNEbDqDCIS4lw3F2CydquEdAdEGByxT/b9JOJp1f+AZSD41QSnTgIGkceNKZMk2yx93OJMDLqTkMZBf5DCeweWrv8rWLoz/v3xGGbkkjxa4hUkb+UGcgxGBlJ5foIZfqlJbWYfPEm9K1+SSh6t3HWFB,iv:lGe3uSXrxlhmr0K1IYv94DWOrHw1LH1GxEHApc96a7M=,tag:cvmdSJ0oVUh13WPsR4+O9Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Qitqbkd3amNJN2tLMjFl
            NjhFM1BMNmJIL0tRL0hvUlNMTGNteTdGVDFnClo0c0I4eGZibjBXQlFRbVowS05v
            YW5Gajl6N1lheUpUWjlobVVCZENFQ2sKLS0tIEVPTVExRXNMWERtRTladWQxcUs1
            RGd4ZXRHOVN0WDJ5cGlMcGVTQlVwd00K2bJFQupt+6E45eloGTXsO7vHnqcBsSfd
            lmv3eQLNpq+832rvGv+rmQajll2+Av5zxxBHSMqPgC2sqsus7YdyIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:22:08Z"
    mac: ENC[AES256_GCM,data:E77tReDzfsTeSljfjXneHdYl4Fjd/6DafGjrAwfP2KEZ069xsxyi3UXLEekU/gn0DOvXeUs/BLDDvhiOyaWzNSuBswCWZVQMZOyvfhZmoeaXKSfL6z3MciXpPCahgZsa2aOl2wGg90pZICHyrO1YSrMVBb4+bDBAe4C163JTDDY=,iv:Q+JQclC63ngpPECh5Uwzs0tc71e+thGS+9iMCPrnCP0=,tag:wcQ1OtZrRTCvV9LgYfQjIw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
