apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3IGNIbXajjK/KnJnzYvhg0h7HSsFTjMwjju/E0I7jmDcAREkoAzmDMMbdd6DKTqDfaW8qpEChQwJpKedlPIMMO95MZ02t0ophWgfyqORTPTYl8Ik+DSOj5TSvAj6ykmQdtbt/0TApBNrC7JVXrSw2ie/hEEe3yXzNqMN7kmcSMPe2C56/A+6ZeMg7p2v6wAj9C5W2Y6RWbTEcHKjrC7YzCgzEQpmKGT4YZZtqU0qE+76rkRHrfRc/u6Zycjb6pwJ20b3GuxSPZqpSvovf8/SGetuml2mcqFt+72qtS/EnQlZeCLZmeKi+XYY+3S8zvLp4y33J+e75OvqbJwiXfY7NQWWJS0+hNtg5B4caiae1BAShHQIm+fadYmzgguJ6EWW,iv:D/QMH3msnd/SHliX3dNl/J1HiSpfTh7FWUMLLfJECQ8=,tag:wVBrB7HfbJhqRAHQOeutEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:V4sUzfV8z/D2qV704PRmyP0v46yZG5/mva57kRZH8YFX6zyPTbMMKRT8LBwSgH/3FTJcuyOVYnn4EemkNK2eHx8xNGEP4rfpLGEBhLbOw7tzrP/k7qSpctUBRTKL8g5gPy8hRNPAltY7HpT6I/wf2RjAekz8tyC0srzqlMq/7QaSefBFz5DorUKtug/aVKvf0H9I5hiO+vjUlGhbzCCjjYZLI5v4PGYq+QMrHPEbNJsqlBxCt5cvoiHwPczwGZmIPlM14B/mTFA9KuUXPg==,iv:vUbYlVcW6oYBZAHu3v8gNZx4JQu25EA+oCWCfNxzRZg=,tag:wv1sVV1/yu6TLqTnKy6gUQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:MG9lxN0axj7+1XJD2ekLmiB+3fvaiELq46aCeeajCNNKVWML2B2da4OuJexK/J0MwHxbdGtDuCx3/e5ViG+616/nAAo6awURMhiN5750a50c8LAAMrz/diXqXBJt0nLmzneJjvA8QiK220n7bJ8jmLO5zYjdIIhUUcRcMjFfJ1TD+AIdfc0IbqpMdCAK+LNfOQ53dtg54G4bAsyReYof7OInHJ+DZM6gr2bA,iv:gGI26q9rpQ34CrjwLPQXXshokO8wPP6lI7SloCL7hHY=,tag:d2PeKs3VAfxVq6sFE1tbKA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N1RwdHVSc3VhWGl6MCtD
            T2duUmVpQWV1MzhtbDhIRVF5YlFDMDg3VjNNCnB5dDM5Tlg2c00wS2o4Z2JMN0lO
            UTljdUwvVTFkMWNreHBRK1NST25ONUkKLS0tIENvUnhUZTh1M0laZHRyQU1ObTdC
            QUttakJOODIyY3BTZCs4R0hOeXRtMEEKg7fMnr5ONdGTZmbliHRZyTM6Q7xtSUgi
            PGCf9kw07efsd/chooxraU9B2Xu63Yx83P9mM7yjNCJNMIbDz8y9Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:05:53Z"
    mac: ENC[AES256_GCM,data:WErDXf1aSUMpxM2JEH3MmRVa5K2+4MHf8WV4OCzQRftoecX25XzsxFtzrYMCn75zQyZdgoDKzegOX+Z4lPjb9ny3Ke32bNAmxAOjZZZpFQv3mBGzCcwjwSVEtqIDn47jxEEkP4hGaPczcxNeecxKckSSraR+i7juYMF+ChCSrYk=,iv:/o5+PpsBA75dww0W25FvwKzFO0oDd2FJXD/q9fwezSg=,tag:Wn5tUmvvZvmmMSvIOZapgQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
