apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:npWAak6lqkQyDsuVbIVlVWynd19jpBCZ2kBODfRnuSTDj3jkr37WC6f36DbEAkHqDX7mHQh52w8ltUFvQ1JInldVev1/IMeBsJ/1/o1D0hYMNWhZDQzcauebihII2lNQZDohyHFIXT3faz+AbdtbSLwB7QccrlvTpww4hJOQZvR+kEtX02VUB7ar0AaQv66m6RIz5XpAae74yhtUNR7OP8rF59AUfuvsD3B9yJKqutek5Ipiroz1Ry03OJMZkliss8CcfTADi/zS5dkX0vwQ97lpOK/udd47tveLaym/jLnpDHNIewQBLWY/PITDsI2VmuxeZwXPShLwobilvGMG/nLmnJZl8+Q1uUq2QwaOz7ekJp3thgeHZLNqXMC+PFT3,iv:Atvzvmf0iZWwb5Vj84zm8Xqc1EWbnt2Rl0X+OHVqt+s=,tag:yw9TdwKCujh2Sxj/MXLLrw==,type:str]
    identity.pub: ENC[AES256_GCM,data:xJ+htyKtgXXXMOhdEUj2j72j2L1Zc1Mwt00vTWrA2pd+Nt2tseeYtdl4tl76PmbKY4o/FpzCar5YxDe5+C9V5NDEXFAV5tuqv4yi6RFpaWKoLTXBydjCVXBQP2pz5uOyJRp1cJ4rL6fwrx9bYw+KfdXQ0aAfbsRX8jHqhRkBT2GsMxsjE/MYfJfLiUzIv/ADBRg0vN6C9FK1OHy6fGLA8Aa1xm0EFpuC00awQK3rumVlHbcjW4GtlKDsK0QF/bTAPbtYHuNH4DZjwyOwPA==,iv:+ckS+GwWhYLVj5dmsUyz7JDlZiRgCH1WyD8z5//9i3A=,tag:+6kLi9cZSqSt0gKohm946Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:7uhdGAF69jn8FKwWa9ZO6N0vHTSuFDKHD//ZfEmDQSHsKwU1cooKgl2GGM7GqGybMwC7cPOrvVxlw6/NZnhv50BAQmdTuOogLJfOKpfsqwzWzBMTfv4+BbRj6UnRoi/w0xmH6E5HlqdSzBJ7fCDoJIj4WgXrWyZSN45Ss3BPUwNlxU0xsffA/kd+luwNryEv+B1t0eNzTaVcBTu/+ovxVgnUZKWJWk+7Ev6R,iv:HTGIP2vzrruelvNEZvQrXNIy+5OIOWtRpd8f6Rs42mg=,tag:7gY3X5aEuyR7MNMerzt1PA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c05pUVVWd1UvMm9IVUVM
            YmpXOGI5c1MvN1RsQUNhQ0hwWjIrR2xYeFM0CjNjeC8zMUplcHlkd0RqbEJvZ0dX
            RmZIUWtCUkc4V1FUMXpNaGhVaHhtRkkKLS0tIHp3ZWNyM25lSWVYQTkzQWtWeVo4
            V3pybktjYTlrTy9TTFVjaUlpN084UFEKUkzagHoK5ZpW3YN+xL4OtcALFh4IKvQd
            FtqCu8+Wrs8Ct1cUcPBfHEVF3pnbEW0l6PmeqUECqEv2iIuIzRyMUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:14:37Z"
    mac: ENC[AES256_GCM,data:EKm0jxn4k8reLB/nupodIokqV7O0U8gSZf3CcHk1glj9lUdREdg0Oj0oF1gwNQFx7gdX3yDdEDdZh206Bs2iYGCTligr/QXt6mCnYhL3Kh2F5tD88vvsS2qjQQPAdet6gCHhS8jnMS9iGgo9XP+X2HtXjiNv/70JRZM6eCeMen0=,iv:X8uXJsWnafZTwXiqyQxY6K+xeub9vBn5r/OJvalzA98=,tag:0JuNUcQKv5Y9/ixkuwAeBA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
