apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MEwL9YN9roc3ZsJbiFKHovmmrkY5gKOnZF5ZZy3aXdiN2pRtuQwhTU8tgWV1dJ9vUHwK3r9QC1Uc2fU8/jkrsng4Zh7uuvdG1fqya/MbwqvzFy1+sDMwExyKlYbNK9j8yVc8VxqPu+G0w4aeXLdpjHmcEuXqXdO+H1qbfLsJdMerkfCPDyR3C7klFKK/jtGn/Q+MApYrOXKLmMaHHKTYroFRQU0DEHtW5fkR1SCV1XQV26pIM8VA2vDONCuWVXA+p1oEujnMY3e9mNazVqz56Zhjw8Mpi1Slel3lpi+1bieez1Lsx2n1qCSVHmpmnQeUuxijdGHI3vOxemLfKXI5VNEhEbcmoBPUeJXRnDBoKJ4aMupl3t99U3l+zcwPeJBy,iv:t3c0/4vpXMNPcC+do49GsIuN7qaDfd42WmIN5utW8bY=,tag:RPF91nayAzTwn2MN8qHTHQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:eowSQbJrWzsHSUc4mLuXKcsKMvYJ1jecCi09n09E3IF0cCM6iAt9oMY/zba6N5rt/RNRx06/bgfAiGDHNA+cZnHx8mOF7csex2f/nV4BkTtcUomRXBe8qNPmxWmn+rwplNyi9XrGxOJoSrUzd44nNZc01Minb30iWEzA1mPcY9yrDxX1ewywJmkG84GiU1wd/dy1mvqQXGI9DxWHcCikoNZM0YjKefV9YAZE7EVW4I8ylB5A7AKQ8Ze0j45cchCmT2uRZB5aaBBuOnjGag==,iv:co4Komou1xCqD5Tacwua4qEButSOGqge38ZaNsMjbg0=,tag:JTzdxiIWbjpDrtIgq418AA==,type:str]
    known_hosts: ENC[AES256_GCM,data:whj9ns3TephhMEzdZe8lhcvBtAvDxP+gSpY6cwoVloC5tN7EUXa5w0VjtwXU03krmtHVD0h14UVQ3gbyr7MZ1PBfs8Ny0WbWKSXlDzdcNr653N8/EpCqhtXyoNyVGEBOwWBE5fg+bD+UX5RUI2VZS85pVQf3ADZRpm1HBjhRcTtE6JKvUTu4nNECJbLEjWP2umNd/fohTTdnvUc68KhdmD63rHiVhOnmU0Uy,iv:cqyzzE8l8RLp7bjigeeUds5a1UQzCfM71qAq9kJHnSA=,tag:65TpktOUGNqWqTu3K7GbOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBha0xBVXJLYjh5aWN6ak5h
            K3RWU2NQS2JPY2s5ME8zYVJ0eWpzdytWdzBBCkszdVlVZDlPakNNcVkreVdyMkZG
            aHJmM2Zkak5ORGc3MXI3eXIrZHliSGMKLS0tIG03KzEyNkNjRzlMVTNHSHFhamFC
            KzNHczFNNEFlSXNZTkZGWmxiRGp6OWcKdBKFsp5JIHgqkoraBfitSBu/70LPpKX/
            yGCuMAE10QKtBaCPP2SBpdCuQOvVC+/yrJVZDWa7LJmmuLKYdf+cLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T17:45:03Z"
    mac: ENC[AES256_GCM,data:UiVJXgv/REEpbJ3RWw/65HvxzHnyGhmqfu4K68XvT64kNv6wpTHZWdq1jN8MS7ZGJIsK9h4CA26jgSvo7vePZWNOvY0yYln7eO7a11ju+OWmT5Ral2FPwq0xnkMvlGUsK65pAOQ1Kd1+uGBZuztm9Tq4tyjLLJKWyEmkluH2erw=,iv:vJaoKmE1U5A4m6l9yuvtEtgLUd7w5jufDJHIk8UYWxo=,tag:H/l+XZVHKgf5z7ddddQZ6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
