apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CYeIIvpYXDJMZ8L0ZrrnJy1vD+clpTv1E7bedv7eV6bpYkwHcAF9lZHu6F+Z2XmpLpwzZqFONVLfJDGY0Ss7qB3i9rby45P6txqjPo8HE1+X2jY2bUD9YmxRacOQse/ncZxkZ6eMpXRjZJhwwUTf4adPoigj7Sy+8DqgyGnntdnHZ3xfVX0NniM219MPDK4xEMrNKBgtgMSeMDhZQ2wQ+wCTXBE3QfCNZv4bDrZ1j/GoDk2MZhrlAPtyj/1WhRr03RcfhhRbTJZ/H1hoT58b6HAVCI3virpS9JRAggF3CaK+SVFLJHtO2ubbm1sAaWK4k4ifrqUml+vGfsrTImIP0uisO50S34eytI5jWphK0bL3k9UkCiHlAYf4Skua8vRF,iv:PathUJYKKuN2IQPDHHlcczvOPp/85SrtQh1LTSP53EA=,tag:3f/RA4YZv10C3GkXXR2W+A==,type:str]
    identity.pub: ENC[AES256_GCM,data:0NF0HAx8or2nIE3jDuhqAm/o6MTOEW67IMjFuipivWgFZy53MN4iWjSJNQ4z8SyzqXC/JJ8N2yEU3xBzdC03XwrlGwFBTEYyF1BIU0ztwvnjRGWJcZQtyen8lvSUjhNKqMAdlJ2v8Ls9KuSuSSmpobMG8jcILhcpLxPvZXm3cJcfxabvyugpySTfwbiRhea3O/RefGUkBqrSAZPvf0iywxxJMxi4ToUudFA+E44LWmbqq+7YHWb7MD7Bu2n7KsqXXua5BFaN+nN9Ka+ZWg==,iv:xnqFVCfteZ+oUH390MIoGnfWTFhaft1Lzmg1heIOiqA=,tag:nLzXM8HgR6mB9dQVZ3n0Ew==,type:str]
    known_hosts: ENC[AES256_GCM,data:FgGeMAGdxB5GKS44aFx5f9g16chZX+txU4HhFB3EJ3rnCklvSGqTbRsgWVT30SMOKcjiXSDR65yPY3POFAlVjFUNg1iWFkJdIMGnMITKDWWTnzUs4TTVnqqEqkDx8wXBw6853kKTYW24iu5eKCWGRngS8BjJzMKVpm8Khv4/dC7kyavD3RGSS9rkoTg7fomegsLqSQelwAgjwooUOI75/VtMNMbRR8NqsQqd,iv:jtWzIO9i1N7gI0aOqEc4GPLMixQaGiRRPpA9IRmZY+Y=,tag:il/cxPsGLONUVddSAPAtlQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMVFRSSsyeFBzT2dLZy9t
            aWkzMGxXUXZjYmdHNDlTdVBiNUViR3JEdGtnClNIdktJYkRoZm9RZTdaYzg5MkJz
            V25OUVhZS1FZS0JTT1YxSDhGK2FlclUKLS0tIHlDUVA5TTRFZEMyMEJiZTh3aFFG
            dHMzQUhHN0lYVDI3MmJ2TkZqVzlNOGsK3L/iLnIfg6wSO6zmTHfJfne4fSmxG8Ir
            PB9NY3zqFnu29JJ8yFI3NNQGwhs/lJeHpFyYJ8DkyQP1zAPPMzUtRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:22:37Z"
    mac: ENC[AES256_GCM,data:JcsMlycJ357W7FH4miuHFEVZbxR4+4C6bwqtY+5cw/bo0ZpS9o5A0gyT3tWot492VUCVmM4NNrP5TG6COmtc3izck/7LkfGQAt82xG26ARTbRLDxCJ0UDSP7Txj5L+F/B5D3ftkoEhdgo2PI3VA3U47TW5X9Ti+xmOdG+CReFII=,iv:CVSDRKMy6w7uHaCiApkepNVRZZzgJYpYaCfgZ2/tfYw=,tag:4s78pJJtzsxOG1GpKTNslQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
