apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PeMBtOMuTyOH1B+BeM300CMKadi4esq4Shr1S7DOqWrzpb1KtJyqE/GmwOUv3gys/Fq4nkxS50LZT6jVTXGfPxFBXDviCNniqCEnCMInKH+xWKbLNHIwHlg7MZXcArI4m5J3ESz0MYpUH7GHUagLrxgaL6En/ZP2UYtZ11vC1jwgJOzcdPNZQRzAnzV9x2K7GODz1Q0/X/+wKfmKvbNkE7rk3n05mPGwJ6lJ13oYDfUStdvo9q2NkutuAMFwFHEl5P0MpSjypUE75TlJSLz98VpYpcnP/xNN6P2qaOAcx5NnfekNj5SesE327cq+kcBJg4eLgwwm8J/C8Gw1tEdIjMYvkOjOWlXadKu5dYzT+YL8mpaUlSjHf+L3O1I+zJLV,iv:+ll1XZGaolWgpCUOewvZyk1ZWgGMMFZT97T+ARzC11s=,tag:GEqPsoj3KItARYpLJNC5Lw==,type:str]
    identity.pub: ENC[AES256_GCM,data:NZ198S/PWoAE77TNYaIjyUx0GIaST3KsrEBNWbDKRFoG/6pvtMO0QorG4IuFk38ycC+4bOFLcUfmUbfdwEuCu6QX8nNlbL86v2unpA0ZYOLQWnxARKMoQ76Tu81UGXkmCCqf6OV0JoPcYMDkLM5i4ThplGZUN4XIqorMiVUUCXY2bSgvwsvqGek5Imz2dqjv7gOE3suPh4TQdkdwdbmljSniDTstHhgrEdM6S2WY0nTwAgsvSdPxrP1ecNMx1Kwwg1Jks3fOxrWmt0jYSA==,iv:vOSYA1XyvYDYTyGCsogsPpaQrF2g2DSXhZsedBlDBWY=,tag:zKCWn9/OERwgLPhAPtJvEw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Xr6l10Yh0MTmkidxo83+w4f0+ceM+e3dwYpo2KewolOmfpPDYEynItbC5/fG4Xd9xjcyBeDy2pQ+TjdE8y+wtjt4Uf9cj6FaDjgw8L3hXsbR3oqph1yocK7ur8U4eYEnE1pzsElbXtufWaZGErh8ceqs0i8AworrcqDTwlAhMXrtN97I3fkZX9ddu1h47zaVUK0jzlznED8JcBmTXamM//KNK9+Jdo8mnRFh,iv:qmsa87SrWIhizIhQP/X81EG4Xugv3QmjLnPafroXizQ=,tag:q/KkbOVWeND1cU9mIy21TQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1JTQXc3dVFwaERBNFdp
            MjhYUVMyUU9aRDVmL3J1ZTRLSDQzYmVxdG1FCmJVMUl3NlpLUVBTU1N5NmVES2pk
            TjA1ckhDd0lJNEszRTVjZjFManFwRGsKLS0tIGR6aURNZ091SGlSTHBnTWo0RVhN
            RkExQTJBZmFnTk9hUElVYXhNM285dUUKGVp6mb2UtRYCMrJDE8Er8Mabs1AqJjCi
            OpVpUnYX3OmbUXychzX0Wyv5DUqXLnls1IiGPheJadeo4eSeUwzOBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T18:08:53Z"
    mac: ENC[AES256_GCM,data:EAqIlffNLz+OhuOy9XJwDUlgn4QJG0oJMJ/4Pey8PPMMgvlpytswVEwSVvXLUyuZ6ZA8p4yk1dEZN+3X/5TcqWcyZhnaLBoFYaUAayJDNXyQvt8/wfqzlI8zxipjv0diUcU2y7bVAxMtdfAF7ky8zVfx0gMgy0sHcZSjusIN9no=,iv:3Epl6UzSlyN/Jr+oODetclhnHHAgpUo6cPYeN5gUVds=,tag:psvVPrDp5T+fSN0h7LiGwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
