apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SITMqxQayFHIfI3GX3X8XScPNQ3H5qdm+n7G8lY07Fn3pXl4lE9V0Eg3/nVnWT3xdLlSO6vn6i9q7hJH6Xyz4hcONprTjzQPOMk5q/fTLr4jGZBJ4DmI4+TTO082npEhb73K2JRGMa8flcWm+SU59cbrbGktFhL5GknmsR6lwy5fqvu+40Wp9gfTCVA0KxPbPydMQbiVbY4Ecw7Z8HPekmwd4SQd3O7QdsQSe9PleVtpEF5BHMtvkzyQaGD2PE+K10lDTBB/XATPMyu1XgpowdH9pbWUbQmAeT5uXSN27RIn0Ub7qY5G/VLN1gB9D500xTwGOR+edG2To96kT8aTyAxd+CTtE0apnN1D/GLABJs48Jutql1a69Cx9D4NC7ow,iv:rqufpl/ik5/lqD7lm7fkDaJqLXxcIVicc2XnyhLlQWM=,tag:vrItv1vE2BveG9T5SXOKgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:jwNjHgm8K05PV/qg+iZnQRWo1+SNXqOPmkkmAK8irOzZWKnIZvFqxycz6jDgCpPGSh6DCW+Cw88tcm/2ThRB7N38hycZTRGhvPxT5e1DKy5nVxCvuYFUAdYHorprINCRRcepP9CqxtHSmDJ0wirrwBvDM5eGqVF1xkFByKjg0SJeaRjBgmKoL5vndPH7buA3Q61i6yAOf8Q6Og2+6tSetbG82fmwVNHnAfM/+3vFa9/kwe+8kma9lEz36QkX4vIz/bUZWIlvazpKSDBM0w==,iv:e0J87rev1lGhk2nVPXIfNz5V0mN8e9+xZwVHy0ILZOo=,tag:ZxpskLC2lqUEBjftdJ7pug==,type:str]
    known_hosts: ENC[AES256_GCM,data:fD7Zy+dA6VnhBenXKw7TspNAXhxu7tBdQ/mgMcT+cJy8UkvtjmfmwowpOJjBZ2hB2U4LnvF9oM44Jx4dbPp32Y94WEyItdw7wc7QaSPUIDRngRhI9JZoO/FewNoluRRtUjL437hIA/HLHqMfpmz6Q+jFLkfnNOPJ2H4QfusdCJjaUh78T3W1PSi3GiPpwHDomNMO5YDRto4LQP1GwKLBgzfXPA2/emn3bXaZ,iv:+BDDfveQkIXHcKMyV/ATDvltZ+VY3yNLra3EIU6MvJE=,tag:duEZv6pkEz/DAVWux1W/kw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNXE5TUVhdEdKbzlOZFEx
            WHoyTEM4aU5RSngrUFk5ZGJxSE9ZNGhTZHkwCkRzb2NzSG5xaVYwU2tKLzB3SUEr
            c09MUTdmRXl5eVhiR0JYVzRuYnhwSkUKLS0tIE5oVlJSOXZ1Ri9BNHpzN1Z2VUZw
            MlVGOU9vN0ZwZ0d5dys4SzBwSit0S00K5nlxbWlkjJj53lUpMAHe04bb08FHR16V
            fy0WEcYGbqmo1gDeh2dnhqP2xC+0t7KL5z4Afk7dMluhwyykeOZWSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:12:09Z"
    mac: ENC[AES256_GCM,data:okmJbsnhLt+ak/k2JKnirCp4dV3az0gEwWwFmKFkKxaDpOz62YhnBMdL1eTpl8NYSfyPOUnh3Sa0boljAeBfYUs62pyN4+VhXUeZnpvPjvs51EymxCh++ZEHkyueFDcBthIBJCxSYZVTtiYps/EH3hvhPC3hs0ZK7QF3h2/taUY=,iv:K46AnPtxENj/PBQDVNb8cxhezOY0hCtD9xIZJHp+Cj8=,tag:Y/NDBvBWKDX9IFbCGzAhVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
