apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LlcYQitNFu47aQKz7/pYxxvEEcff79DL5/CT/ZsGrERZqysn1vA41fKNy47O1nsIMzhAPhQA33Wv7xmPWE/142qtEdkMLR7C9lglL9/ToPX1DFEIDCtJ/UePYbtL4nM3PckawD/SNQlwZI+o3n9j1F8HHiWD+o+4HFnhQoBLy9n8FOc1qrB9u+T6L86WjG8S1GlMrtMkDh4QLEI8GrqET61LGVlXJLJp3i+MnuTIlIAR7TdCkKv7+fMPHf5fhKb9zWLDs9kJWUmCJsSxruAIwGibRLk8qEqSCtfR4/Uajb8QXcKUR8kQUlsaTF1UfH0sI21IqBd7B2tONNRSexVHxOFOalgWDwxw3oiD3tPEqOoYT6zT1GCuRlSHAUdxN69N,iv:4dRBN3LLJw6g4rDepS7Ue0pVsUS9jrP0u8iQBQ2fNv8=,tag:VeHBLDrLke4E/B3n+Csw4g==,type:str]
    identity.pub: ENC[AES256_GCM,data:BLBWXKrJ3kdzz/U146Qc9G162oj6c6RNK8ksA/5T+3w4fAyEQcPzlSUzm8pS/ggTOmdU5Q4yVkokMz7y069Oz0GQjpPRCKsqgeJgzui+A8IZdYwmo4z0oN/5iaqIkU4CFRJkAM5lUVc235rQtTg3XgRhDTeL58UdX2JTmWoL0yaRM94eBLD6xpLq32s194RWIz7ZJPM+OU5lwcZ1kLr9opKEILQt4LL2G8iTzvg18G25gB2cKwpMFJRqpc8+a6m34vEKlTZya3NDoyk0ZQ==,iv:/KS4G0T6sZqjc6CpIiFNHQr9YrIX1sLtFsmJFd1aHXQ=,tag:VEfaMTV6uEGCUhr2ChYCtw==,type:str]
    known_hosts: ENC[AES256_GCM,data:uPzNPngg5/25RchoC86nRy8t49GFXs71rjLAi5gQkGkv3NxqVLJ3m7OkfJxqksMRDWZmboZX+VoBz6m/WpUhCOgSBtgYcbDWIQS6XgTvXBhG2NWyutSiT8wwVuXRGxRnHazvXP9KVAkWmss9htGzaMDeIMbaujTJ7SLrbiymo0pCy5QgPgDpbYxK92bsoOdkTCayoBxkTsl/Mr1Kt0BvqKXn6ZIreZ061yC4,iv:FSA9gxZHaw5vm/pukAQmLybahuuQDwcZiEiEXsW//MU=,tag:2kV1pzTisCGETpKyl5p0Gg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWGFqMEwyWlVsNk50L1Ar
            STJpQUhNSEZDRi9WRDNLcXZLMEs1VlM3Y0VzCnFpbDZEa0EwTGR5QkJsRjRSNzVm
            WkNzd0IvQXdFTTUrUWEyWXBPRzZiK1UKLS0tIGlCVjAxb1pZQ1MzaGdNdzUwMTk3
            RXo1QXVmSy9SODRLMWNzdmZ1bmFoTGsK1JFPTzvhJY4NOz2zkDhgLP0CovTd0+Qd
            VguRsg5XvuVKOA9Dq9MdCNp4Nm4I1gvnCKDBVVRvwbr8vdBl0q7E4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:42:29Z"
    mac: ENC[AES256_GCM,data:OPNxV0ge7NUcMtInUKIrGlLyzIWMj5xKa+GpKU7XUT9VTvAM8Fono6o9gA1uo5H9fC2Dg+BCbOnx2d7Hc6OvVW4RR1ViyGvAwJ5sg4WMdrqIr/zO2UZLOzGvHoOD7GOzyhkdjA51w2R7oYKn3Xo4YinYNYdscPgNXEfB/u1JKwI=,iv:8/4bRDTwLg5zu8Iz4ybdCys/VpYX6MY1fE8d8HR1JA0=,tag:I0kunpIUxUQpibN7my9z6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
