apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:KKsXkG77pFZgnz70eMtbtyUKyv5k+x5Lj1wbOzl0hJiI/82Yyjmr+pUb7uOQKannvDrz4gKYXle44tmGFM/gwysV/s1OhTgQNriyihO5VT7QJDA/GlYZPhKUg/qnCWIvKIE+MEh3WfGTZ/KkZjBZGv0HJ9kRSD74vw==,iv:T+WdygseaEfFmiwPTyjolfSu5u116sLZkUnA+2a43H4=,tag:BDG4x++pIsX7PHeduyW4GA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNlBQTFJxdHBHVUtUVzRm
            VUFTQW0rZjN4TkdVcXVtZ2U5WjhDSjRjSlZNCkRVZVRZWDhhanI5ekVSeWxJeVpZ
            TksyK1lyeXdic2VLUUhKTlorWXRRS0UKLS0tIGNpWS9oc2M5U3VrZlV3d1hVUGFy
            czRQYWhwb25qcWhMUnc3MzkzNEwvMDgK1Rc5yLHvJO2HKAOYgTwlMK11LfkXCEaj
            aaZrD2I1A1ZEgRk2QFpnLrP9DH9h6cKiNWOKTQ4T3CYBe6ltbRQrlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:10:30Z"
    mac: ENC[AES256_GCM,data:zzK9F4Vhg38q7BjjIrQwZkOYvHO25d7z1ZPtzptaR3vxTirK0CNnd+WnWfC2LOd4fDCy/Hlqc9+pbkA06hBucxPXV7twbwXa0mp7y0KBHquJVLML/xLCUnSAl5672OWUikX4h5+QbR5iizdlCJoRDQzJu3/piBQG/BZhSMNxL68=,iv:PoXS1t9Kyb/WUXUCbsYI5TKWvAsmUMWzkiI/FH3kguw=,tag:OGNHimx0niG+FXE6y9Zo5g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
