apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Q94ceDgbbVAi1zIs+PXkza4RAQntf7i0DalK6b60DiiHR5WUrwG4FBMt5MV42o083CuCBzajfCE0Kb0AzcUrRJ8TzgPacEqhoLuIHn/CIVVT9yzksHS89NnQj473JY7j/z9zUaaqDufmuC7mo5MUF/NAIyp73A6Xhg==,iv:Xajr6dMTqUP5LzXCf62rGH1Cgq/su0gPpesddrDBkGI=,tag:lGJ4oNlY2r57XRwKT+0qHQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOVZWSmFPdFFxdi9mVkpU
            elBqUU1qVVVObFBSQzM3N1dOTHVvQzRTdEg4CjcyaFlRaDFCMFRoMUF2N3RrNFZj
            NG9zS0ZSalo5Wi95L0xxcWtUYzBJNXMKLS0tIFJrZGNuYzNVL0lWekk5QU1zcExT
            UVRRRlBPSXZmeEdzc1JIQ2g2QUNpSE0K5c1EgscjDXYWPvMdr50G+VdTjJXDhegb
            +n7HKKMxlrdvY7tnnsNwPH+zGK9mhTNlQN/rhiBMi+CeKzEEcMFnyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:15:07Z"
    mac: ENC[AES256_GCM,data:Q3Q37Lcx61hWmUxlq5gKvK91MSETtiiy/4iTUvsrZ0/9+7/K9YuNdOi0viNm3fWnoDe/FLzj6uzXhUygfrw2vVXHuuNjZLxOUI6mTWXs0B4JY1KMGoVQrmwtkpjgM7P02vmDhfJY26U3YKjUiAjnRKCa/YfVA7Nqxpk4LYLSygA=,iv:RkxUk6Y69UtzfXADcFAFchJnHV93lPJM1dER00OAXAc=,tag:UC9g8bJ8imUC9+0qzh9jng==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
