apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:SpyFhJ6GayllqRUAlJQV0Z4V1KLDujdEFFsVWktQmnbuoMGNCkwvSgyG9fwBRGseHoK6iKRlsu/h5xrdUV6Wg/rfURd+OTJ6pMPf39zQM7GAGodmO0H2ODu0ThxFH22mk26YnB5xjsDeKQMhOOK1rR/+S7Fi/P719g==,iv:qlxA3jIJ9gTw4Th8s9uQ43YnKyozyNx7zbrVv72vaoQ=,tag:SIXMY9zM1qgrSKzSR+zmPQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNXJxLzl2Vm1yZUUrYlBt
            b2JuNVdocXpuUll1LzdZZkNHdkVDRU82Q1FJCjk3ejd0ZjNaSDBmKyt1VC9SRjc1
            QS9EdXkvbTBLU3MyTWxEb1MvdWRDN1EKLS0tIGc1NWZTY3ZwNzhvRUk4Y2dtT2dI
            aSs2akVRdnFYUWZDNFFSZXBXcHNiNWMK+oY/ytZWB0SACRMVes01ZKoN9WvdZkpN
            wXppc2QlQkV0O2KBx5N2I7HSrOeLqmP2CA4nVJS46AgDH5/bbTMxgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:42:29Z"
    mac: ENC[AES256_GCM,data:rS3REbsJusaegKZ8W3j5SF0UVXirSxHm4RCBUaMAldpSXQ8q5IRDGFQTsJSQRmQeiXQo4QxB2p9ChzA3It0GqSe7d6/WRsKwlFs+plVKwaujEwS+nufxDFdgi4RTlQR6DT1pr5XxIHMlQoZ1C4R6lG6hctpo4SEhD+dWHAhnYRc=,iv:1gpJvdVCv0pd/1tH8JflWLg+G9gfmIVgbTYXGrYjv0Y=,tag:13wjLNBLSqx61Y/2FdBKtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
