apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:J215wpAHOVzNfD3JNwpBbU+hHqJeMXCyaHLFQ6suEcboJ7Zs8c9yshLOLv0hZRzpnjZZhmrkjI3lqlG+rSfyzLGYSNLuDArpqZ0XYr4ET1zpt6is4seZ1RKhOzgSkTIG7AlLYQamJztz/E+ZZwJmRVA3KD+9ilhhLhqLbw==,iv:nWiOyO0zj1ilQU9UAHWYgodZzsvojrAOKju6PhZE2h0=,tag:+6GJpxurCgowLlNTEeneMw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:YNrmmy311u8KXquIrXC0xRzYyTBRTRrKutWg4ZeZitPWJxmEaKT4bkCdEZggo9r4pyQlYS07VVj7mB57rJZ6jg==,iv:8Vktya5+g8sptVyvnZGVX39Rbvu2KWcNj38jAFCjsOo=,tag:1pYj68mxkq9IxX1GM6bmtQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:xf5ckmbEk66l8jBfP0jWQ8vo7B3TmYswdfrFntf2xkympxcyoGGL22fn/xw9h7XYpX8mLorb8Xy9EJDXqScSmJCIAIeaSJwlnD4ZAlNe/unG8yzjq1hWXa8=,iv:EaYyh6TdmKlR4+/3m2CydJdP0BMjm2v+yNxhE4Rog1g=,tag:nGVKjo23mvEwi/kcY+u2XA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa3pvdDVibTRMZmNqQ0xG
            OWVjZzh2dkpPbEhYYTQ3SmtSSjZMNXVCeG1rCjVINkZsL2JlcytMRURaYitKKzdM
            WW1KaDk0bHF2OVg3WTNreGNTVVBQc2cKLS0tIDRtbkFNT3JvanBJUDVSWDh3RER5
            aXlxZTJRVmtobkVWNnBQRFhSS2I3aDQKyJzYhHHd//eWUEEFRXMRsRYYz4kGeerT
            vtmgQAWLp/GVPZ7pXvr6P8PAolay3LmTMZvf99KRaDVOcaBXzjGzVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:05:38Z"
    mac: ENC[AES256_GCM,data:H5Ze1IyrpLGQA9KtFHLCngUs1uZW1B4ZRS3+qJ2gISiPT16UfIO0Y4UJVHxGfheOQNfLosVRkLN76l6yFrrob3YgMhHnhCASwdiqpOJNhGdKeRORu3NEZS3OcNNCn9ySdanTP0sXq7nkrdzU21P0FpoCNRb64rFEf+yGDLuKtGY=,iv:Nu2pzfXgn5oSy/W57Hee8HQsuGJCr1rWU/kKdJ3naHA=,tag:0o3tNbkoqy9sifbp49DSXw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
