apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:zzNv5eDcjQdtH6Gv0d5XzTUpAUz3FrLkLP/iufmc1GC9qZ8uncO05I1+kSb1dra3nelS6Y25zrb+o/V4edKc2sHN06YE5BA9Bti9ReFU4ZXR6FfWG8/dlhLtUTGp30lJq31ix7vVsUQXl1n30hCJ5pmCyf5CuUCSKA==,iv:BdKqnBNUkgyl4zm2CJiYmVxo8I6kaZ3GX4zmoqxRnIM=,tag:QvZy0iCUz1kDWmbza+J0Ag==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST1hMeHBJb0tqejB5Q3E4
            QVFSdFIvVkFrL0RMUFgyY0lQSFRLdDV4bnlVCnZ3OWRkVmw2T2taTVJweWVQanJr
            U3d5Wk5lQkxyT2h1aTNJYlNKd3ZqLzgKLS0tIEhWMnBPNmhmcEpqb3ZiOWdsUDd5
            R0dZdkViWTJiUkRoUnNvRG83S2RUS2cKdmA/1X2G1Vi0acRPTdjqITlaiAfp/nZt
            9LNNjgTW+E0LqRp0bRFbSajGrvPQG8B1T9RZHjZmkltgL+0JtAOsUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:14:23Z"
    mac: ENC[AES256_GCM,data:zV23Dpx7EkT8R1kQK6kP2XvPZBhZ6/ScCX6rLmBLaV1xmcZhnquy8fK3yGmxgfdT44CtPnIsY20UrD9kjJe8HQGhPRJuaDjQmH45Nlm+TThLBeqWzZ+cpeP/bbxZV7/FSFg9fK4wL0rwDpw4zzo/D9f9H4Js+k8Vh1RbcrkP57A=,iv:UscaBStK2ijsiKXnr9MacMWtHCY+WOIqVbB75m0HOgE=,tag:ktCwK1/JWfvv5DiSoj+0Xg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
