apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:XGBh9PJEdi6A99g1hjQK+GpO37FLPYeXHXAaFnoiHjBjv0sKQMihR1P16R/hvmNou+4IzljFNR5npHiG5VLeyZ3FSfpMc2vCjSwbpk4vmEpPzH3UcncoOCSMo2guIzA3ShaAbaLuLNOg787HABEysAD19O7fwYy09xlX2g==,iv:TQp80kMh8mZ3GqGnPzRFxLrz3h2SNEulEGoANIRIlLE=,tag:MNa6jh3OgZUwbYmrrs9cKQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:m6C3m6j3XYUvr/owTcxz2IxAhP1ZVtvD9LFdLvTptiMCv9V8KCPJC4gRobGE38/Acyx2f35OZEezUJIbnkLQKQ==,iv:5MkfJeUrHFRUdbHF8SbOL64Cr0hayeLMVq0QcIsD7D4=,tag:SZbR/LosZ2DRkIfNhASXzQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:OmiOzA3RfeAQpLLoBbRfq2geedAagVfmLwK9mrzteIxgImrpfMlrepIwxAibCEjeNZ6d3t18nmWDUkLsCCUkmw3H9WcIkXurXl5jkVcEtgcawOR0bq52kQw=,iv:Ucce97g/dYTDW8eJYcUEMwcBsOiLpBfei+WRB05bDpY=,tag:JW+YkTAhJ/gSeAJnYd1XZQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOVVrRzhUMi8vZnI5MU5U
            VFYxNnl1SVQrUVBuMytNMExYR2dZOXREeW5ZCktKcWUrREFPMHNFR1A4N0dyWDlL
            TnFYSlhqUVFOd0YxcWFObmlGQlhhL0kKLS0tIEt6OFpXTW5Ta0pDMnAxNmFZWGJX
            Sk5Oc21Tc2JtRnBSSCtaQ1JEMHBYOE0KkJ6Q1yz4v9Y18hxP1zSFnw7sVjbzH3Ak
            SRvCREN2yVavHZwWQlj47Y6RikiHhOG8KE4AFr61lYnrL4WAQFk9OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T13:36:34Z"
    mac: ENC[AES256_GCM,data:wA9Jv7VJOQtut+2+WbvHKv7PvAeN9+udGHtaMCNHjFXZJJkD7V6mwbAYU6WEnJ2NYLdtF8iYgOZNXULjxNUXur8gm9xo+6Tu1DeBi6wWd1HQLhUw76pfBFRvA49E5RwdGfm8sB00L9GBg+BRt6fpfWQ2phimd2mh+7E2tYQFoHM=,iv:JcEUaxk00lw698enBpNYW6pogcd1PhkQLpoRvawGm7E=,tag:bKfAt5Dm/7TycT/JcNw+oA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
