apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:s67mjXxstoOOufIZlF2hQIjH9eaMCHBcpL0HPdjK32ebt0Jk6Cbi78wAGP3kZO1hOQQbd8t23bojsfsoBoBUk+7M0LtxZJQsPxtIIJlednngri5UCYPtvq0739gEtxSE0zbbfTrjPyL1i+pcuckcwKjTSjwZFfwj64pdyw==,iv:ozAOsXkqpfU7iM8/4t8SVe7rgrNRHSrDE2TiWuNrHVE=,tag:ySrv23dnE1sfYfbt120Tuw==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:povT2q1WLUiwhGtHZ8Eo3yHq4E2nBpm/Go1nhLtNPMPzg8RF1zG9RNNiiobPaxd5gpFTN2orbcEizcqVUlrDXw==,iv:wnJyMc1FCEsDj1NJF4TZ0Fks616oNaE13fMTk42efb0=,tag:sKJnoBNOCJfLOAq6vleVQA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:LJZurDS/XcOZgKnyAD4M/gaaZOPessn3b+wAaATprV+IX9GLww1LH69bFWLCsNjZbeXjbQiH9NeY9cwHFUdjcKre8j6iyQtYHwQy9CTJSj0HUH5Tea7U6Gg=,iv:45DDYkV4HXe4TWD1PrxOKY2npeLtq/aBLgaSv4kD7C4=,tag:vziIBotRhMI7v+UCCGy+7w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySERTNThRZXE4WDRrZHpo
            di95QjJTMm1UbkxJMFZWdnUxckZiMWFZUFhjCnpuSTN6ZjVQbXFBQW1RTHI5YjF3
            U1ZsMDc1NFhycHMwTVByQkxXWm85R3cKLS0tIDZkY0J4OWJkcmhkKzJ4VGs0dkdK
            VWhIS3doSFIveCs3YmlxdjJUNVlxdm8Kmt/F3BQXsKl60XaYJWcxF1Uo8e3zZpHy
            WVGG8Vv1arSGZUsfm6Biyp8LpRc7LZv6/cM3nHsQwnPfLSzLt0Ubzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:12:09Z"
    mac: ENC[AES256_GCM,data:KSgTBEmy12tt8dqRB4CIIXJAGmCsVmPtmSkEuBXTasEP0TJhmOz0I6IJEHfgsK/wJHvh+pV7dDCwRm4Czc863xq48r4OAV+MdIVc2S1ZqF20azKRO5DKHix9HBrBpdnH2NLMa8Ozw7LKiG6V1qYok2VIEuh3DUuUZeLR+hYQV+s=,iv:HPMCi50VqeUHbZM0DfyGMnFyGXmvP9wir6oYjX96stc=,tag:G0D9UeJqd/ji8PQmAP5QkQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
