apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:cL6BwCsYEGuY2tk9UJy2OauePYUSLX77ZY/cFFX37+/il44yq1y1sMKFcC0WvIJzgKzyWUp5KAPkJsZEIOX4roQtSnq3zvpfO/fnX8tsVeYnTthbP92JBetl2pg19KjO7llkNp9d/3I6TMUPaeNK4yvPLyKcFclmjw==,iv:8vYRjGvmFKYTLvMaQNChejhgqgmaCoJPIaY0Lzz15VU=,tag:w8JNYCCFnJUb8uIKdD//3A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdVhjOWx6TmlRNmpjdDFG
            SjhHVlFLdUhrdW9pRFA1cEtaS3o4ckFqWlhJCktYaktxRm9FYlZyK0cxbzlvL29a
            bWJaT0JmR2xaOE0zbk1yZWMxOHd6RU0KLS0tIDgvc2ZHdFg3QW5YMmxZdDIyK1hM
            T1FXQk9KNFZ4aUR1eDlkSDd6N3JqbE0KuOne8A6TRUIGVDuOIue27RREERwY/i5E
            rsNQs+X2MuP9sdRzRtiQCzzK00nzidFVvc1DZ8x5qGYhushMXDXneg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:06:19Z"
    mac: ENC[AES256_GCM,data:P4wfCvHWkMuOWpBfp5RIIeqWF1hoz9Mb5RTLHf5A5Qv1LFyAtlrbIKHRPOzAvk+2omyCa1WAJTJAZLi9M/wvuh5EVJ5L0pNN5YlvSFFqxtkrpFSL6TUd101vHU4VpZ3aYZ+szrTWgnP/kSIJ4nkQ6UOD1WyCjhuyNkdPXAw07zw=,iv:hqF4KYTuCLIUgOFSRvRVzv3qFcMwgLF6NfCJBwvVlfA=,tag:Uu5OHNaa+ADTODGfUHFdYQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
