apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:fnH8qAjw8YNEFxVXb61fMec5IXr8G1y/436sSbBvyclsXeM9mones2aNOxIbFJEpxOKmlnEDbCE6Hdl2gtTW/QqjvKppLIpV1YGaE/fLn8GL7EXDL2vhroQuPsLREbwpcjAi8yBCwnf7pVpr/TSv5/QUBIgCa6YcEQ==,iv:R7oUTN7nI1BjrwCg2M3/TsAIcvs0DhFkT+dSMYNsWeI=,tag:Y4umrExSeIKzuXBjBIBh9w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRS91RTZGaVkvNGhITS9K
            KzdlM1oxYXBua2M1YjVGQW1iaVFiWkNDZVFZClRad0Jsak9tWVJSS1JEZ2gxYzlV
            dndsQUZUUmRHcmNCdEt4SWp5RXpaMW8KLS0tIDJvZnlCUENvYkxRQnhBR2N5Ynkz
            Yy9LdnBESFlCaldMa2RXWnF5KzZZY00KeDZWcXfEjEQKlsPQiMEBrPpL/hjYjFBC
            vnYwT41qH/04wiCsPh2J2neiLs4Bzlcclnyr8yGgQOktOuT2g+yIpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T09:03:46Z"
    mac: ENC[AES256_GCM,data://hEWhVPaN1fN1PayCGjUT2D19aXIF0VBMgBC+/qWvgX9vBLO/J42xRIRjvxxikLYQgR85Pb14rABNJUzP8PO5kIzGwKVV4L2qBdppXAxx5X7o31TzsTxue4QAmVEH9mOmbOb10MsyPwXHOC4/tsP8bPnnuf1l8ZkVW78C470es=,iv:B8JIVSs6xTUttMoQAEq6vfYmJZQh8izbF2HRvxeTfzk=,tag:2oUpb7V15LjDk1hg9PwP6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
