apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:9+zD6b4B27eUlTLIJQ68sVyOhVuY3KLGPF0yYbel+aW6I0Ozp76Xf0j1AvymxVr5DKOs2XQofpXNV9wF3UpSwI6+Lex5r19OKRs/EB/JeSo4JJFQ1DERtzo16Bq2v+EYem1pqfgjLdQGNJXEyLiBl/RZ0qmrIjJpoA==,iv:ID9VnlXKQVXM+w/N7cJqUCl4Ys9FL6mnZlaiSsrDWho=,tag:Uie6MvTKLMN6ZYUbdShVFg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTHp5YzhUUERuR0gwclBa
            QkFPZ1hBUU5reEpnZTZKZ0h2Z1YwNzIvZ1RZCm03d01aVHVWT0g5ZGRYZ0VvdlpZ
            RHJpQWJUTFdTV1hJWUw2V3ZDbjFHMTAKLS0tIFZIVkxaTGFPbWJjWHlnM0JMcC9v
            ZlZKZWZ4ZDduVFNIeVF0VVFabnl1ZmsKzjYoHWCqoVVPPPq+olPtFQoq9ua0cKy8
            F66vqtJ4PGI5BJGulhzdqBAKryVIGAwHYYppKC+FOlMO0pu/CEXcnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:22:38Z"
    mac: ENC[AES256_GCM,data:7ZQJi7W69Kd7n4YFqq9slmE9SB0MU0zls6dMNQ9zDVieOHRbhC750GFlWuLkY1SjvgSD/N2w0QHzG4KyeRW0sts5tQi0RzB4VxRf50rJjdbDljCElr/+Tn2+Lp2Kaa+u8GA1w4coTYaHqhoJIkWohaMrO3xFPEdH8X9yd69YLQg=,iv:xUjuyzG/k54EDZv3ZEbWUzsbpwEdu1JeFQOBq17zYNE=,tag:RVwzL8KK2uOe1vfSYuB8uw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
