apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:8CnpprOBe8F1b33wpSDnuE291k4SZ6ECBOIkGNNoEGcgYyP1ZKJh+ftJrpjazQpX7QaAKOwjfv+PytDfKRVV1y0mkBcLvmktnHKkLgL2yeRqQ0OZKYJvN27Jwv2vK9KKndBf0wkkMCXbE3Ek7jd9zcMcLJUqGkkMuw==,iv:FUWPIxhdAs3WdnGnbR/qF0D4Jmyyc9gtg25t0MhZIj0=,tag:HcYJFLgJsTAYh8sebweNOA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa3dyZ2dGTUg2NUdNMzEx
            L3k1T0JmZEZUVGFNd0lDQ01CRjVwc1JhZ1NBCmp1QnlYYm9nRFBBdUZRbWt4MVlB
            K3piOTIwT1cyVCtsRnpzWlpKRld6ck0KLS0tIGVJRlNYRmxnZ2lGU0hCamZ6eTF6
            Unp3UVJZNDhQV0NqbmFyK25xb0dFc2MKkbbCOCpqeFNLKqccT/JWvGy34v3WHYdE
            6v1BvoSmxrrz5lmtf4Z5M+qjKiead+xdJ3afhcrXMP6gtnIemO7CzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:14:37Z"
    mac: ENC[AES256_GCM,data:M+USx/L+teNXRjKMODiGa0HP5YqBMgFc+l1LvsF0t4tDTjl3C5BiCkkdPbypTusXRhJbAHPz7ob8wEiyFFIdMqyFeUTq1u83UNnH8YV1LHtQmBu3pBSV2+cuf+pITDN8R+VL9WVYoQoLal5ikphc1HI8ErKQwwHhXom4/XsCgf0=,iv:HZWNM19JceCC4LurHmpHRvqGYFh9vy2pyjxm80yXzZg=,tag:hVVauXYIcRqgEs+GzvBvqQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
