apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ZenFPyI523rOATMvGx5yvJa3WeZij4G4F+Gkb6ajHGnIM1Ohw6sm2hfJw/kythQs1awFXg+qA20bSzDp5Ib2NrLnb/DqZUeWt3YIVIpJBAV2PTIubNh/KftFb5yMqdmyHsOlOr0MFuTR7Xa+UL4zA3044IpPRrmxuA==,iv:7Q/rysQvH0Q8vDBh2m4KFEVWKbNLHfO3cyoi0EgACK0=,tag:XOebtJQkiCWzt0gtearKKw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd1RVblBaYUNjRlRwV1Rh
            ZHZIdXNmYjZhZzRvZ05VY2xrSk1EL1h1bm1FCmtGWFh2bHNjZWVwNlFrZE1WWE9S
            Ny95WUxMbkJidUl5QTVodDVmOVBxZ0EKLS0tIE9WVHhGN21BNUJXSmJpc0dBL3du
            UGZRdzlJeDV1QlB5WFJMTE9jQjQ1L0UKa5ar1Li5DmYhlp/7ZOPH7ys2HuG7PcT2
            lpFN9/oEHPs+qLzzpCz4QWMRTOaZAkCOaXDBEGjX+mseTHq59VOFxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T20:36:13Z"
    mac: ENC[AES256_GCM,data:ICHn+vgFrVOHmnPL+KlxIKx2iIKb83DETxjclqGbUlNKPWKXD/4xNAu8GhFJcYrIHzc+s+av0ykM5oN/pnO4Hm2gnJEQOJ+qkOlN+9LUXoOCaB9/vQqz0ejcjGog9C/y7UxiT/JxHwAoXggSVVtgimQpKxRmtkjhh4VKxz9vqTE=,iv:Yp3g9TTFV24uf0ceeTgUBgj9pJLMfL5uoNqk/WH/GUM=,tag:IMx290Ia3MoiLn9bre9Rtg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
