apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:vlZYaCpjxpm13BHDLkN4exmsl0MkP89VFaXf02j1Tfb66Nb7FuGHnC1/gAWb8W5AG54NHCG1KtaeGeA2LyhKSbPTnoqo0zwa61J3V2h3Nmxz45zjSbqCgBVlh2MZEijanE+LG7DWjOdiJdFMofP9HfgxvRHMl8CflQ==,iv:M/+Rn/CfkujPEkwLWa/oyZ6a78DgY4hiH99sNTRkZOo=,tag:eLt+GWLD+6jjim3dIL2FRw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VTgvVzhITTRLU0xZZFpQ
            N1FZOEpOVVNLblVTT0wzdm4rWEJ6S3ArVmh3CnNmY3NpZWVjS2hJRXFMMlEwQ09n
            ZFd6cEhKK2lxWksvWm1pUDJGdGxvWGsKLS0tIDJ5ZmsrQUVIcmJDekMrWDdxYzJk
            WCtkMHNicUQrMlF3Sy9mRCtRQUFlRGcK8aPYsQtAm8BfxUhQmV3j8ZFm258t9rh7
            DUUlIq0OgVzEKRg51v4K1CpK2KHHUgenMrqql1irnTZ14NVkh3+WMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:19:57Z"
    mac: ENC[AES256_GCM,data:M46Zhnn444577Y1GO+LNQibqpNtV5yLljCXC1GYpE8xdE/X+QXPRYJ9BqaiAznSDXuaXcdIKgri5DNEWnWIfI4KKOe5YE9ceu3Y8lGbzlWGTj8AUri2nC4a27fWK+kmTAK9FiukD9JSHqATNeA3Hq+ztS/x7zdDGe7Ry/p9UNd0=,iv:BNZ9fSprUvFz7+xjH7bFFRtnd9pjNYU2cEGXdDm/4Zo=,tag:/126QxvpJJvX0xvqZ8oynQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
