apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:w1k9p8AEyFzylU8v/0xs6apd6avy/g5/rWI8ftP9Q3UD2PcxKbaeT3cHNGk6vugQ8Bsm6tKd/BilYf8KYDV/eCqLYnWffZianaiQSwKQ2miGyhPuQLJ96seiSUC6NVEcq6qCBzUd+FaHCKGxywOBcES2m2HwmOENNQ==,iv:yye8D2YCc7VPjCnNTCqflvtLhoa2x1CzO6pbQmJyIRA=,tag:GHapt4Prfe3IB7w68K2n5A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta0NPVU9ObG1GL2J5eHJo
            cm5TTEljNTVtVUdITnk2ZnFxMDNHcEJaYkJrCkJER0hQZnFXSlJHVTA4amI5WWwx
            TmpJcHh6NS9PVHJaTGtnbjVRa0RIVG8KLS0tIDdZd3UxMkNvSjFHQ1FhSi9iMzFE
            OGFYOWZRdUlUbWJZNEd3cFVwaktySDAK89rYjv+hAftguZvQjzgFMEyxn/fdiccf
            IkJCm1p2zJKWeEiguUoGn92Z5RlooHZon/n7Ef6IwmxsSQwJott8xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T20:35:22Z"
    mac: ENC[AES256_GCM,data:D28x3Wo5oqHk3SBzxB4hngwggGS9C0cq9vl2r//ZaYSL5sAmr76BgDJVkGIV2CGiF7gf5gZtdN+YOYUT6sJxQMbxY5HGpMIQfRbo01C4xQ7fid6u9kbVbNHVZpQNghvh0BRABjTlTayFiAk3YqcFVrMsvlPaJM/N38puh9J3OIA=,iv:jXxUASKgDtAV/SGzcN0t4bFEMPGaJR/81eVOeBzRc1w=,tag:T6YoihJ6bJd5IPK7bZUCdw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
