apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:X0s5/PQBpZ08m2JVz9bHd3tS8kcPZ0vM6gpKANk591BDBPyr1z0idTmV+nXlAWVq6i2M8o5ZeJjRocV0vC262QtzLvQnpSK0HLqw55jdHtn/+3OhgCqQwYP9scGT/hDD7Ooal1c7UnyGV3VxJ5ww1drg/zaQg+5P6g==,iv:f42PKVMLhpOENx/Y3Ym0vPFxVX8dD1Yz+Z8CXr0n7Y0=,tag:7ZCE2dNk81uCFEfE2RBZ+Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZG0wME8yQXhaWEpsUk81
            UzdYdFdualV4eXdOVExzeHZxMzVkVHduUzN3CitKWGNUeldrRFZUKzBTUWRyOW1x
            d0d1d09QZzBjZVFpdU9rWkIvYVV3VzAKLS0tIFNGSWNPbEprNnFrRmZaOFVnT2NX
            VHNZOVdudHIzUlRYZDMrUUhSbElkQ2MKY0k9SFF9INMapnkxKiEBE0KLOC6Bi3PZ
            lofMOmfhXEeSOcrtcXF6PnA1+SCsjc2Ct06RZXTpbvWISSy8fKWT1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:16:52Z"
    mac: ENC[AES256_GCM,data:/uJxUzSktGnvxPh0MX4Gr+EKT2HXCU7v1U7XR3NAiAT26At0SOnQbBrftyUzmW/L/EQoaVKFJzQ+p3Kn4SeuAX59htbwOkuLIPzdGmtvGbb0NZG6gelP4b4pfw84u95du9JyWhCg1VbYA/GUMrVIHimHuaI0h6qHfOshxUn/LfQ=,iv:gEA5QTk6TySGntbs3KVBGiJc4MBX8Rf3vOWF/eGriEc=,tag:n+/mr8Am+jfM5LwLVEsP7w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
