apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:UsREJknwUpQ466GHufFny4744Q8rJqBJ1ufY7hvuGmJUo6ce0iEocON0NivrKa7JkR5W5Augg4XTbldpcmxncFJQfOPm9e7MPpXJO4d3qaOP/tplMzv2cQkv0gx/HNqPA8JzhKahdQQ0DRAgVuYW08cdIvtMvCi1mKEsyA==,iv:/kc5dzjlJeJi2qbySj9pxgjusGIW29Q5rN4nIUTMJN0=,tag:kdRJh86g3Hd1oqCS+R/TnQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:id7tFdV7u3tbkqWzuba9GCkzeyZhqNWkC6MbceE/oNiwjZYVX/ZF5Dvs4P0S2P7vw7qBQVZGLFi8JpJlXyEoFA==,iv:8mP83akb7/Ln6+hyOwDzkK3U/uD3ihKgXsaeVhwecS4=,tag:YOCBQfAkoy7S1MaaneCNrg==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:A/hjTdaxAaboc1xMgZMpHUN+0CLjF/kYqwzVR13KFzL3KzFkYRmodkWe8nDTqDUwIiTU1uzjPKvg5rEXpxhOsllKO7Nh5LLDa1mkrKXiSxiOCrdx6Crjytg=,iv:C1ILZSz+hR9svVb7fKR2gDdi6/5yvJmn1Ud0VmV3HY4=,tag:424SGp2CJxeW90OrAtWs2Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdmhLQlpSdE9pbHdFcWg0
            ajNGdVBTTTM1NG80RGhMd1FxUU5zQzhvbTNJCmROWEVhQkRmQm9VYU9LVWJpUmN2
            RUVtTTJWbW9peWJEdWJQbUY0d0hvd0kKLS0tIENTV0cvZUttamZzQ1ZFb2pxM0hP
            RzF6bmNUWFVraGNDbFUwNGVRVmsrYWsKd8NYcap9DTUAKSmRQJtdRB/OW7ZpbPp1
            kphPIDI4M0R2HU0GZWviwlCz0OlrsL1DYW/UXPNCid8mCRASlFXRQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:30:33Z"
    mac: ENC[AES256_GCM,data:PFaZHoLhEuMeF5qJQUfGIvLCb13FJRFyFkK5pFYAZWpzIF+Voi66sx38oWGmgqy3FLkXNkzJAdeA/f4gmmVpea6Mbfi9LUhqUjF4ugdoGMFhy2O+6tNTiXW0mjbjO32n8s6QcMT0OjIgIvd3Z3LWc7EGzalncbdHE+L/VGZkGdM=,iv:ReQAQ9t0G5LMtd9zOGNghwNvn+u4YpAONBpXGJMIpKY=,tag:P4zNvnU2KwxgP0yuJ/2ICQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
