apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
data:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:rh3eaQDVqNdSGjn/v7jkYM4FrKZh68AwxsOsMmvXaxSbBA4WWrhtqY3wYkEg7glcMDZpEQA/W4Az+SSz1UBoSb302JnsOoFoJ6f8ifrw2J5erlNOo6kuSdEkou8iPcLUwu+CHpCRgsCqkgYLys0O1KA9AuVDnRrFvA==,iv:SNTU6sV4/EQb7Z38S6HBNHvN2tKqwH4CjrhjSzW64oM=,tag:F8DwkFjnsBDrfTGHpUObfw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY2krK1V0ZTVQSG1xNnNK
            Z0RMVW11bnZ4bFNLZGMySS9SNFk0OTMxZFVVCnRjek40ZHhwaStEc2s1cVlzbE5u
            OGxTOTVqV3BIa04xZm9mb3BXdDBRdTQKLS0tIGgzV0p3YisvU0hoMzE1Q21pSGM3
            S1hUNkgzSXlqOUsrZ1pNaVhlKzJkaU0K8xl8c5IiokcpSqhjLeK2y2R8E8OlNqfk
            PpWPGZycBD5QK4qoMk/ldEY65Gh81tIVQXu6z5t+Ba8jBZlD0+OhRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T18:16:19Z"
    mac: ENC[AES256_GCM,data:nQTk9t4WRTJFxOFQO0pQ5fF108736RqOQPnVBZlijP8qwmNPuCMxAceaPGbofKT6+AXSUAAfaU0TX2aw+riqkIHkRSiLRolOvRW/+xORFutPTBKmpiGXqFWwzzfOSTJ9QpIDEk+Bs0XfEtdtmBkxP+DSp6N1t5+G+EqlvwOCPV8=,iv:zH27PRuTui7zUDCsXTRUbyWzxEdrXBnkAI4rrGWoDzo=,tag:Gz7HBgpGonHBbB+DFDKYig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
