apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ZcCyDMxBP5Eo5w/zD1q+TaoVt8x26JjxBkxMhsjcBAwi1k2dtjeD0vH46CmlEm1VnisnxntgtMI5XyK64D2FS0j1CmaZebznoZ8HaqjmrazK0s/2vRBerAx5OLHJG2nUW0egwajAfg6Ne+pbg2gW5qfeIjJCXE6UiA==,iv:gGd+c4AY/yCyeNZYNFcFy/u/S4F0EyfjoDD5QbsrnHU=,tag:ZiDoCwRaOVo/ipCyK1nKXQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTmFsMFpjWXV6U2ZCYjdO
            aklwNXBSdnRYWU9sZDFTMEdIWG1iR3NHRjFRCjB6SWFUMUtYT1YxdWZ0anQyN2Fm
            YVlSMlM1WHRRVWpXeEJDOUU2TnBwdVUKLS0tIEpsRDZSYWV5d1llcG9qOXR6Qzcy
            bnFPbWs1WS85WWdocHZkSStxenE3ODgKxbupA7ybfQujt7gkWpxiluPLdNeNqmO3
            LV2eY4poWLb1POprkR+D8kgA/0Z9LfH0bsX+lQOsTW1m/qDpDdn1QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T21:05:53Z"
    mac: ENC[AES256_GCM,data:Oqw2VcOKordkkqkqG4UymKLXr3upQBOgNTXFXSqgkLfK4MrCbgewveZA11pPzzYP8YmuG/7lIOg+BtvgA3z/dmpAjRf1D6AgDjxHDmf+U/ovM1CuwUxd3NmxWZOs/G8a1y2h58ZIVULnbH7TFXXe5ZeDOXnKwEuewOCfbLoVmR4=,iv:6HWR2rwoWUDNgXQT4WuzEiImd0wvSqEEep5I70SKrrY=,tag:SFWk7veuLAWUQM92xsUGDA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
