apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:aGG+LbsCpUsm+SN5x9VS8y9DHixJtwYwO01gbV0KnZCQQacE4aecvZ5ky/D8vW/TeV91FVhEdyr36Ps75xh+PN9ThMx1vnleiUgbJo/NeYr/7e+2GE+qLP6OpAVxti/udXx05R12TP+nTN93lHZvbrg+ArJuqURbx+hkkg==,iv:tw56kWohTH8ThI2lXKJggsyBduic0MXutcUyqR/St7o=,tag:OGEUjf8BOXz4un1cSn28/Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:Qjz3hGhnhRZwHwnDV9uY8uP3QTap0lT29fgm0ECdJ2Pw4ifCkhJJKgKKEs8Vr56Xwk14AgS0yDaXCkD4gpIjPw==,iv:5XZmBpyXXsz4cZxVEiv6FN0JA27TDZ91rbqZrVOuWyw=,tag:/jx+70+BSAnbY8gbzjjn9w==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:JRCLW0NCvD7FORBmc6oOz9gS0/jw/DGPXNmjR0e3+BYxIPNsph+1lohydU7N/oBnLC60jy0yUR52JHFSa9V0weOHAeVjcPcRqAGT8a1B9FP3HA71/wkDDSM=,iv:0y4bKiAuWUetX8Vzl87XqWobcagAO3tLe/dyHre8DSs=,tag:sqQFDjwME7kt9gr+f5by4g==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubkFNZ2pHMm5qWXplYlU5
            VjNZR3JvYnNlRzBKWXZaTGxkOWJKc05aKzNVCmZqWklTTmwvYjJNVnhqNzI4MzhX
            bllSMVQxemgxUW5WQ3o0SGRScDhKVzgKLS0tIG5FMmY1V0lHM3FndTV2c1NHTVZL
            ellSUm9jRm5sWTNWVElHa2hEbGJTMHcKRNyb7NQXBYybrsIB4nLC9DEMqoqyDlvS
            lbD2FvS/PH2h8heWZOCxopHjK8cOCCtIOXDXnDgW+OTfG8at9kIZog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T14:41:38Z"
    mac: ENC[AES256_GCM,data:RkIuitHLzwyBMkuRQBwNE4TkquaZ0ulRY3GfiXlA1aagf1unCaej4N0ARGBhkOatiaV6YrVU//zuf5s0y+lo3G+GpBRoexPCaCYF2AoZQovIvZhMJkqafzynT+H0nX4FvNyTkY1SbDDAqYQ3+RZJjHHC5R+7QtGEVMAFsPxQ/D0=,iv:6Bp6pULQxEZMcrznqxbxKOLppPT3ybmMURJyjn0663Y=,tag:5YEcpfwRz/0IkGP1cdsIrg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
