apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:fnH8qAjw8YNEFxVXb61fMec5IXr8G1y/436sSbBvyclsXeM9mones2aNOxIbFJEpxOKmlnEDbCE6Hdl2gtTW/QqjvKppLIpV1YGaE/fLn8GL7EXDL2vhroQuPsLREbwpcjAi8yBCwnf7pVpr/TSv5/QUBIgCa6YcEQ==,iv:R7oUTN7nI1BjrwCg2M3/TsAIcvs0DhFkT+dSMYNsWeI=,tag:Y4umrExSeIKzuXBjBIBh9w==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:8ycBCoNwmFaqDp+4yamVzufk3W5hwwQr20YeMX3SCCSooycLh/Ca95N22w9MO6svKNm1uLAC9D1P9T2RV3QpCQ==,iv:Nor1DFQouti6K/+aB8VdGU6Ja/Ittk8yY87I6RPcU0Q=,tag:rdE5gQxzVv26/SK8TLrjMw==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:uca9+FkVF2Z1ZMH9hCD+4YvhnjdP8yI9lyI9lM3d0Ux5gkwbGbUD7g2SSQ37s/xgp62to9O3WbpLxDcsRuQO0kQvmXkdbYq8HY3LE/Mnew48+nQHnGCxfds=,iv:HA+wyt3Nyi/Z1Lc2C9ATvFypLJIGQUMSSPLzKM1/CZI=,tag:ol5Nl1ChpfwhBeRPmmN4vQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRS91RTZGaVkvNGhITS9K
            KzdlM1oxYXBua2M1YjVGQW1iaVFiWkNDZVFZClRad0Jsak9tWVJSS1JEZ2gxYzlV
            dndsQUZUUmRHcmNCdEt4SWp5RXpaMW8KLS0tIDJvZnlCUENvYkxRQnhBR2N5Ynkz
            Yy9LdnBESFlCaldMa2RXWnF5KzZZY00KeDZWcXfEjEQKlsPQiMEBrPpL/hjYjFBC
            vnYwT41qH/04wiCsPh2J2neiLs4Bzlcclnyr8yGgQOktOuT2g+yIpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T10:35:57Z"
    mac: ENC[AES256_GCM,data:8laQ3z7MvNm+RLqMWNq/xJQD8av/79Vn7quP6Hm5zsPgoH54rfBMbM7MVRCacZ4WGYVV/Gw7SftsgSCtf8RcPa9hQRiAze7MpreUWHUNNH+ZACxVkSiPIFqAxqUVluJ25gyLXLEITe8axEQ9aCeAjo3m4byB+4NcVmGbmxnZh1g=,iv:URO0NPGxV9EDrHB6kpwBgiTE753XY6tXPhctmA254CY=,tag:AgBNqc6JYQGYpdNmD0WbMw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
