apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:6/d9vhsT16Kw6bSJpPWFbi3fL7r901nyRu5O2RAQAN0HYi10TgJGjAje8bLiLYQYIknEhM5bBfm40UHvI6d8/kCZChbcflH4EdY2p7sshesxkzgfECUYE8cy4vuK2E6/JICe7hHlDIGf/mOclCkgvWOBJ6piqK3Q6aBeCQ==,iv:FgkfykHzd4boC8ytQGaWVyiLVkye7zVPjNQ0x1ZzmDk=,tag:ZxAIcBlWeTsh5xvWunOOLQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:8CqbbDPxasEFjgrnKINNyCibcFiY84jIzcpygjSmlLE0QHFxVKXA/vz+Nl+COja75yvwmKT9Lvabmu3SFdMgNw==,iv:c26nQUl3Tpa+RsFrD1DWrEHHyjpy1/n6WliHHmCRxkk=,tag:vXs2HgI8XXOpUxRHAfQTug==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:E3gLdDw9oynhRveDS74vmCjb9GCpIOzYSHiPDrgF3PygwYh2+LvVMAT6gVRVvOYCa4F6pGIuza66E4k6ji98ptcSRbLNee6BlPM+jcq6fDYNB9A28vLCZ0k=,iv:/SHDfg2Swg0Lj7AGEL96wLE4gOLX2NJZRMi3wZJYYjE=,tag:i7yd4ZAv646xpWCrNUTgrA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbGFOaENQNFUycmxUelVv
            MGFXc2t1QXpiWDRkMTAyT2ZBMnF5UEJiMjBrCjdDdFFSTWk2NHA4R2dZbmtiMVd3
            ZHJQWktRWS9iaWlwWUcyZUlXVm9ybXcKLS0tIGJucnFFUEdrM0pMUFRJa2E4cWJG
            QzBwZGlkNHpoQXZKNWl2MWJPNTJxNncKEbm2uf/TMKlN94nv/IWwMcr36qO+CVjB
            xr9bFpS8Rh/5Q4F+eIRb52v+xTsJeP3LGpEgLE8qXWtLGPKKNTp9Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T16:58:27Z"
    mac: ENC[AES256_GCM,data:Kh/j+pBSK3jYwtou5TpeLwRNxg+UVu+rptNpLXpTNFa1lMj8geV22KKblib7yKzbnwEV0/Qt/2StgDAQOBXNzXUmph/JKKJqHfqpnJCYatxQAlU8iayHNwmypOmw8wOO/PpN88eIxbcwT+jA1GGJNxQb/cTI0HHcTMXzM6l/b8o=,iv:1DCqzqXmDm93Bn1VXW1FOFrz2pzcbw5s3YWRH/TNKaI=,tag:+TQc1zawawvno0Iw/qV1eQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
