apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:2blMVdEfdPVAj/FbpojRREoAEHv1ZUwMdHBzm1IfE+xu82cCWX97xA2B5IjmJvxM5GE1UZVWvZuF783jWvnMoZ+3fKzKwZC9lxr2YY84fPyssqD0VIWB8iNqgeKwj0TRjH4WhL2JDDWi0ncJcBelu4mXTXUo8rZNvupcCA==,iv:Zso9ADFXfQiKeZVxVIjJXFJG8BGgSi/w9NtlSVo+3k4=,tag:SE0z74ZtznkNHDjlkUpTqg==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:8ycBCoNwmFaqDp+4yamVzufk3W5hwwQr20YeMX3SCCSooycLh/Ca95N22w9MO6svKNm1uLAC9D1P9T2RV3QpCQ==,iv:Nor1DFQouti6K/+aB8VdGU6Ja/Ittk8yY87I6RPcU0Q=,tag:rdE5gQxzVv26/SK8TLrjMw==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:J2NXoFq0v/bYCsJB9Fnb8w4AHNV47xxC5qhCg5FCq/U0HGaCGPdEfzqrnQVklKgVprfE9RuTuG1YYezc2pFgX7zx6nCcXZXCSdXKVd2BS6W27694BLvfP+krVRM=,iv:msEppfIB+AJFD7xExbECDTx/qqg40adJsXql2pJjjak=,tag:ns9SkrN4i8wbCgSKubsHFw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRS91RTZGaVkvNGhITS9K
            KzdlM1oxYXBua2M1YjVGQW1iaVFiWkNDZVFZClRad0Jsak9tWVJSS1JEZ2gxYzlV
            dndsQUZUUmRHcmNCdEt4SWp5RXpaMW8KLS0tIDJvZnlCUENvYkxRQnhBR2N5Ynkz
            Yy9LdnBESFlCaldMa2RXWnF5KzZZY00KeDZWcXfEjEQKlsPQiMEBrPpL/hjYjFBC
            vnYwT41qH/04wiCsPh2J2neiLs4Bzlcclnyr8yGgQOktOuT2g+yIpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T13:05:56Z"
    mac: ENC[AES256_GCM,data:XmfZuQcf5pVgbrGsz1Vp4dsG3RnN6dszz91X2GYYzxBnGeOWmXWcDV1fa92Oyao6kdY3Delg76uELtaorAfOrLhSS4q3KeWSDSxNiUPcUXOnwwdvrFVgUww/R+CGzvcnUb2mZn6AoNj9H7exZYR3oT6PjkUxI0nnEKUBtf4Ux2E=,iv:+A3G7xVOUgjqCLmP5M+FuPAGFYwScrjE0MfYpAFHg7k=,tag:jZMYlb1unr+aMTt7eNDtLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
