apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:2YxYJxUIw6kRG8F7/9uAQ7XbBjB53BqGKDwhgOleJRlP3Rx2cyMX7QBKTm/8c98f4mFXXSMKkJp/MRCT5O11rgrlwIrUoIMqwXu3EYe50JPpLTt85OS3798rBnTazhpUnyts592KgtXdiBCMumQ3pAKve7oTBWKk0w==,iv:4Ctc5XOPrY1pYkl2XLqd33MsKYndPucn7o21X9prRSA=,tag:m90fIKBRwm1H6XQ4FT+MMw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVnhNSTN5cFBhWHlqR0Zm
            TXhieGd1QVk2K2RneFZrbVlmeDZGM0pheURZCmxNZVVQTmoydndLSy8zVHhUNlQr
            Vk9icjFtTnF3QVAramZCU2N4UVJmcUUKLS0tIEE2blNQRlhFbno1N1ZpYW5IcDFQ
            UXdSRjdNZ3NtaHR3NjhhQTIwUTMxOTAK9nQD9cmwgQfTvAHltqFuVm2/2jFhWi1J
            y2fc/5d2b/QFeNZzoth4Eq2ZtWt4Pbxi597moDQ/Z2MBAtY7epBOmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T18:08:53Z"
    mac: ENC[AES256_GCM,data:9CVr2eMSIGGgSgWGstojAAeQy2H66+H/F9cZV2dZE707p+srnFoumNnGszDZzF4wN8iE3cYrAKiDUBOrUv+REINPQKX4LV1+GsI8DOx5rYd07peeHDl2PX1tgwLOEYAT/0crfS5hwB+kPBZ4EQ8MO4tI8qczk+/H3dXpROKFbN4=,iv:mZCU1KaVd+Q6TpM5y0hMUlMQV5HLw44mUqGeFUshw2Q=,tag:oZ3oUO0xG0A2EoGceVFjQA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
