apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - alertmanagerconfig.yaml
  - alertmanager.secret.yaml
  - etc.secret.yaml
  - helm-release.yaml
  - scrapeconfig.yaml
components:
  - ../../../../components/notifications/discord  - TEMPalertmanagerconfig.yaml
  - TEMPalertmanagervalues.yaml
