---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 25.25.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    global:
      stopAll: false

    credentials:
      minio:
        type: s3
        url: "http://${S3_URL}"
        bucket: "${S3_BUCKET}-immich"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: immich.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: cloudflare
          homepage:
            enabled: true
            group: "Media"
            widget:
              custom:
                key: "${HP_API_IMMICH}"
                version: "2"

    persistence:
      library:
        type: nfs
        server: 192.168.1.50
        path: /mnt/SSD_Cluster/app_immich/library
      uploads:
        type: nfs
        server: 192.168.1.50
        path: /mnt/SSD_Cluster/app_immich/uploads
      backups:
        type: nfs
        server: 192.168.1.50
        path: /mnt/SSD_Cluster/app_immich/backups
      thumbs:
        type: nfs
        server: 192.168.1.50
        path: /mnt/SSD_Cluster/app_immich/thumbs
      profile:
        type: nfs
        server: 192.168.1.50
        path: /mnt/SSD_Cluster/app_immich/profile
      video:
        type: nfs
        server: 192.168.1.50
        path: /mnt/SSD_Cluster/app_immich/encoded-video
      afbeeldingen:
        enabled: true
        type: nfs
        server: 192.168.1.50
        path: /mnt/HDD_Cluster/Afbeeldingen
        mountPath: /mnt/afbeeldingen
        readOnly: true
        targetSelector:
          main:
            main: {}
          microservices:
            microservices: {}

    cnpg:
      main:
        cluster:
          singleNode: true
        # mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions
        backups:
          enabled: false
          credentials: minio
          retentionPolicy: "14d"
          # revision: "1"
        recovery:
          credentials: minio
          # revision: ""