apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ext-denon/ks.yaml
  - ext-plugwise/ks.yaml
  - ext-smartctl/ks.yaml
  - ext-truenas/ks.yaml
  - ext-unifi/ks.yaml
components:
  - ../../components/notifications/discord