apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ext-smartctl
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/external-services/ext-smartctl/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

