name: Test Cluster Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: boemel-runner

    steps:
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Show kubectl version
        run: kubectl version --client

      - name: List namespaces
        run: kubectl get namespaces