name: Test Cluster Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: boemel-runner

    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede # v4

      - name: Show kubectl version
        run: kubectl version --client

      - name: List own namespace
        run: kubectl get pods -n actions-runner-system